### ISSUE TITLE
Monitoring of non-Theano quantities on training data

### ISSUE THREAD

**Issue by rizar** [mila-udem/blocks#1006]
Currently only `DataStreamMonitoring` can accept instance of `MonitoredQuantity`. Ideally, `TrainingDataMonitoring` should also be able to work with them. The implementation would be very similar to what we currently do in `DatasetEvalutor`.

**Comment by dwf** [comment]
First I've heard of MonitoredQuantity. What is it and why does a simple callable not suffice?

**Comment by rizar** [comment]
You can find it [here](https://github.com/mila-udem/blocks/blob/master/blocks/monitoring/aggregation.py#L176). It is more involved than a callback for two reasons:

- it defines a set of Theano variables that it needs to compute its value
- it defines how its values should be aggregated

It it especially useful for all kinds of models that generated structured outputs. One can compute complex statistics of what is generated, e.g. edit distance from the groundtruth. I can imagine it being quite useful for training generative models of images as well, e.g. if you have some code that can evaluates the quality of your samples, which you don't want to reimplement in Theano.

**Comment by rizar** [comment]
Fixed by #1007
