### ISSUE TITLE
fuel loads data from disk while blocks is doing computation

### ISSUE THREAD

**Issue by Beronx86** [mila-udem/blocks#1017]
When the data is very large, it cannot be loaded in the memory. Fuel load several mini-batches into memory every time at this circumstance. It is desirable to load the next few mini-batches while computing the current mini-batches. How can I implement this?

**Comment by bartvm** [comment]
The data preprocessing server is what you're looking for: http://fuel.readthedocs.org/en/latest/server.html

**Comment by Beronx86** [comment]
@bartvm It works. Thank you very much.
