### ISSUE TITLE
Travis weirdness

### ISSUE THREAD

**Issue by bartvm** [mila-udem/blocks#1018]
As noticed by @dmitriy-serdyuk in https://github.com/mila-udem/blocks/pull/1013#issuecomment-192341151 and @dwf in https://github.com/mila-udem/blocks/pull/1016#issuecomment-192010418, Travis is throwing a tantrum again.

Theano complains about `g++` missing and not being able to load `scipy.linalg.blas`. The issues with `libgfortran` are reminiscent of https://github.com/mila-udem/blocks/issues/836, but the SciPy version hasn't changed since, so I'm not sure why this suddenly resurfaced...

**Comment by dmitriy-serdyuk** [comment]
Seems, it's fixed now.
