### ISSUE TITLE
Is there a way to retrieve predictions on a test set?

### ISSUE THREAD

**Issue by aukejw** [mila-udem/blocks#1033]
I've tried to add an extension to training that monitors the output of the network, something along the lines of 
```
DataStreamMonitoring(data_stream=test_stream, 
                     variables=[test_output_tensor], 
                     after_epoch=True)
```

.. but this seems to aggregate the results: my datastream consists of 300 batches of size 100, but the output is of size (100, 10). When I check the `main_loop.log`, it contains only an entry at row 300 (actually 301, but zero-indexed). I checked in `DatastreamEvaluator.evaluate`, and the entire batch is processed. Does this monitor take the mean over batches by default? 

I couldn't find any relevant information in the docs, nor could I find any blocks-examples where predictions are generated. 

If anyone can point me in the right direction, I'd greatly appreciate it.

**Comment by dandxy89** [comment]
Currently working on something similar to this for a project. Will update tomorrow.

**Comment by dwf** [comment]
On Wed, Mar 16, 2016 at 10:19 AM, Auke Wiggers <notifications@github.com>
wrote:

> I've tried to add an extension to training that monitors the output of the
> network, something along the lines of
>
> DataStreamMonitoring(data_stream=test_stream, variables=[test_output_tensor], after_epoch=True)
>
> .. but this seems to aggregate the results: my datastream consists of 300
> batches of size 100, but the output is of size (100, 10). When I check the
> main_loop.log, it contains only an entry at row 300. I checked in
> DatastreamEvaluator.evaluate, and the entire batch is processed. Does
> this monitor take the mean over batches by default?
>
Yes, normally this is used for monitoring stuff like error rates and so on.

> I couldn't find any relevant information in the docs, nor could I find any
> blocks-examples where convnet-predictions are generated. Unsurprisingly,
> most contributors care more about validation scores ;)
>
> If anyone can point me in the right direction, I'd greatly appreciate it.
>
So, an extension that makes predictions and stores them on an attribute of
the extension would be fairly simple to write. You could probably reuse
DatasetEvaluator by writing a custom aggregation scheme.

**Comment by aukejw** [comment]
@dwf thanks for the explanation, at least I now know that I should stop trying to subclass DataStreamMonitor. If I implement a Concatenate aggregation scheme, it should be easy to create a SimpleExtension.

@dandyx: awaiting your update!

**Comment by dwf** [comment]
Just a note that concatenating after every step is probably going to waste
lots of memory. I'd recommend just accumulating array batches in a list and
concatenating once in an 'after_epoch' call, or something like that.

**Comment by aukejw** [comment]
Wow, that's much easier than trying to use DatasetEvaluator.
```
class PredictDataStream(SimpleExtension):
    """
    Predict for a given datastream.
    """
    def __init__(self, data_stream, output_tensor, **kwargs):
        self.data_stream = data_stream
        self.output_tensor = output_tensor
        self.prediction = None

        kwargs.setdefault('after_training', True)
        super(PredictDataStream, self).__init__(**kwargs)

        cg = ComputationGraph(output_tensor)
        self.theano_function = cg.get_theano_function()

    def do(self, which_callback, *args):
        prediction = []
        for batch in self.data_stream.get_epoch_iterator(as_dict=True):
            prediction.extend(self.theano_function(**batch))
        self.prediction = np.concatenate(prediction, axis=0)
```

Only issue is that I'll need to get the extension's attribute `prediction` later on, so I cannot use the typical 
`extensions = [OtherExtension(...), PredictDataStream(...)]`

but rather need to say something like
```
predictor = PredictDataStream(...)
extensions = [OtherExtension(...), predictor]
print predictor.prediction
```

Is this similar to what you had in mind?

**Comment by dwf** [comment]
Sure, or you could listen for the `after_training` callback and print it then (or save it to disk periodically with `numpy.save`, or what have you).

**Comment by aukejw** [comment]
Thanks for the tips! In hindsight it's quite easy (if you know where to look).  

I'll close the issue. Let me know if you think this'll make a useful contribution for blocks-extras, I was planning on working out the details and tests anyway.

**Comment by dwf** [comment]
Sounds like it would, sure. Feel free to open a pull request (it'd nice to at least have one smoke test for it though.)

**Comment by rizar** [comment]
Hey guys,

Just found this thread. An alternative to the solution that you found is to
subclass `MonitoredQuantity` from blocks/monitoring/aggregation.py. This is
the base class that allows to monitor things which can not be expressed as
Theano variables and/or have to be aggregated in a very custom way (your
case). You can pass instances of this class to `DataStreamMonitoring` and
`TrainingDataMonitoring`.

**Comment by aukejw** [comment]
Thanks for the pointer, @rizar. In hindsight, the tools were already there - at the time, I just didn't know how to use them. In my defense, the MonitoredQuantity was still fairly new. I'm keeping a close eye on [this issue](https://github.com/mila-udem/blocks/issues/1006).

**Comment by rizar** [comment]
Actually, this issue should be closed, we have already merged the
respective pull request.
