### ISSUE TITLE
Can I turn off a part of the cost according a schedule in blocks.

### ISSUE THREAD

**Issue by Beronx86** [mila-udem/blocks#1034]
My model doesn't work well, so I want to add a module to the original model. The added module may be used to pre-train the model, or it may be trained together with the original model (sort of multi-task learning). In short, it is desirable to turn off a part of the final cost. Can I do this in blocks?

**Comment by dwf** [comment]
If you want to shut it off after a certain number of steps/epochs, you can multiply that term of your cost with a shared variable set to a scalar 1 (e.g. created by `switch_var = blocks.utils.shared_floatx(1)`). Then you can use something like
```python
SharedVariableModifier(switch_var, toolz.functoolz.flip(operator.mul, 0), after_n_epochs=50)
```
or `after_n_iterations` or whatever timing you want (see the SimpleExtension docs).

If you want it to satisfy some other conditions you can always subclass SharedVariableModifier (or write your own extension from scratch, it's not that hard, just have a look at the SimpleExtension docs).

P.S. questions like this are better suited for the mailing list.
