### ISSUE TITLE
Problem installing Bricks

### ISSUE THREAD

**Issue by tubaybb321** [mila-udem/blocks#1036]
I had cloned the bricks repository and then, since I wanted to play with the code, followed the installation instructions and used the following command:

`$ pip install -e file:.#egg=blocks[test,docs] -r requirements.txt`

Unfortunately,  it generated the following error:

```
M6800:~/Downloads/blocks$ pip install -e file:.#egg=blocks[test,docs] -r requirements.txt
Obtaining file:.#egg=blocks
  Running setup.py (path:/.#egg=blocks/setup.py) egg_info for package from file:.#egg=blocks
    Error [Errno 2] No such file or directory: '/.#egg=blocks' while executing command python setup.py egg_info
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1146, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 680, in call_subprocess
    cwd=cwd, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/.#egg=blocks'

Storing debug log for failure in /tmp/tmpmD_Llh


```
I was not certain how to handle this (i.e. Googling didn't help), so, instead I installed the way I normally do when I want to easily play with code:

`sudo python setup.py develop`

I'm not certain if my original problem was do to an error on my part, or to an issue you should be made aware of, but in case it's the latter now you know. In either case I'm wondering if there is a reason not to have used the develop command with setup.py, since it seems fairly simple.

**Comment by bartvm** [comment]
`pip install -e 'file:.#egg=blocks[test,docs]' -r requirements.txt` works just fine for me with pip 8.1.0 and setuptools 20.2.2. Please try updating those two packages, it will probably fix it.

**Comment by tubaybb321** [comment]
Thanks. That did it.
