### ISSUE TITLE
A wired bug when calculating loss in a class or out of a class.

### ISSUE THREAD

**Issue by Beronx86** [mila-udem/blocks#1038]
Hi,
Now, I have a wired bug in my code. I use `BinaryCrossEntropy` layer and `TensorVariable.sum(axis=0).mean()` to calculate 2 parts of the loss. When I put the loss calculation in the class' apply function, the code works well. But if I put the the loss calculation out of the class, Nan occures during the training? I think the code logics are equivalent.
Are there any clues to locate or solve the problem?

**Comment by bartvm** [comment]
I don't really understand what you're doing. Could you provide a code example?

**Comment by rizar** [comment]
Closed due to inactivity.
