### ISSUE TITLE
Multiple Batchnorm bricks cause variable naming conflict

### ISSUE THREAD

**Issue by o1lo01ol1o** [mila-udem/blocks#1039]
The parent bricks' name should be passed to the variable names on initialization so the following doesn't happen:

```
ValueError: ('this shared variable already has an update expression, (population_mean, Elemwise{add,no_inplace}.0)\n\nOriginal exception:\n\tValueError: this shared variable already has an update expression, (population_mean, Elemwise{add,no_inplace}.0)', (population_mean, Elemwise{add,no_inplace}.0))
```

**Comment by dwf** [comment]
That check is based on object identity, not on name. So it looks like you are passing two different updates. Did you pass `allow_duplicates=True` to `get_batch_norm_updates`? If so, it's your responsibility to figure out what to do with duplicates before using them.

**Comment by o1lo01ol1o** [comment]
Ah, I see.  Yes I allowed duplicates;  I'll guess I'll figure out something sensible to do with them.  Thanks.

**Comment by dwf** [comment]
Note that using teh raw updates probably isn't a great idea either, I usually do a slow moving average.

**Comment by o1lo01ol1o** [comment]
Yes, was going to do that but forgot that my multiple applications would also need to be resolved.  Is there a way to filter the updates by the brick that produced them?

**Comment by dwf** [comment]
Something like ```python
from blocks.filter import get_brick

iters = itertools.groupby(sorted(updates, key=lambda x: get_brick(x[0])), lambda x: get_brick(x[0]))
```
iters is then a list of sub-iterators, each of which contains only updates related to a given brick.

**Comment by dwf** [comment]
Er rather, it will be a collection of (key, iterator) tuples, where the key is the brick.

**Comment by o1lo01ol1o** [comment]
That's helpful, thanks
