### ISSUE TITLE
input argument to lstm.apply dimensionality

### ISSUE THREAD

**Issue by sygi** [mila-udem/blocks#1040]
In the docs to the LSTM's [`apply` function](http://blocks.readthedocs.org/en/latest/api/bricks.html?highlight=LSTM#blocks.bricks.recurrent.LSTM.apply) one can read "inputs (TensorVariable) – The 2 dimensional matrix of inputs in the shape (batch_size, features * 4)".
As far as I understand and see in some examples, it is also possible (and reasonable) to pass 3-dimensional matrix here of shape (batch_size, length_of_the_sequence, features * 4).
1. Am I right? Will it do the expected thing, i.e. pass first element of the sequence (vector of length features) to the LSTM, output something and change hidden state, then pass the second element of the sequence to that changed state, etc.?
2. If so, do you think it's a good idea to put that information to the docs? I spent some time today trying to figure it out, and still am unsure. I can do the change.

**Comment by rizar** [comment]
The `apply` function describes how one step of LSTM is done. Thanks to the @recurrent decorator it is wrapped with, it can also be used process the whole input sequence. AFAIK, our [rnn tutorial](http://blocks.readthedocs.org/en/latest/rnn.html) should explain these things. Can you please take a look?

**Comment by sygi** [comment]
Thanks, I took a look at the tutorial and I think I understand things now. But it doesn't explicitly state what the dimensions of the tensor passed to `apply` mean, neither. I created a short PR, do you think it is fine (and, what's more important, correct)?

It's also a pity that `iterate` argument passed to `apply` is not documented outside of tutorial, although I understand why it is the way it is.
