### ISSUE TITLE
truncate_gradient should be argument to theano.scan

### ISSUE THREAD

**Issue by moore269** [mila-udem/blocks#1046]
It seems like blocks should have the functionality to truncate gradients for BPTT in RNN.

I think this line should be edited.
https://github.com/mila-udem/blocks/blob/0e1696d39d9c73e93f63cba5d0b4f75ecce07dfb/blocks/bricks/recurrent.py#L223 

Discussion
https://groups.google.com/forum/#!topic/blocks-users/g25REC5ackQ

**Comment by rizar** [comment]
It seems to me that it would be sufficient to support passing of arbitrary arguments to `theano.scan` through an additional keyword argument of `recurrent_apply`. @moore269 , do you agree?

**Comment by dwf** [comment]
@rizar Am I wrong in thinking that would require you to subclass e.g. LSTM in order to train an LSTM with truncated gradient?

**Comment by rizar** [comment]
I don't think so. What I have in mind is just adding
scan_kwargs={'truncate_gradient': True} to your lstm.apply(...) call.

**Comment by dmitriy-serdyuk** [comment]
This is very needed feature in blocks, indeed. We just discussed it with @Thrandis several days ago.

**Comment by rizar** [comment]
Well, it would take about 5 lines of code to implement..

**Comment by dwf** [comment]
:+1:

**Comment by moore269** [comment]
@rizar yes, that should work
