### ISSUE TITLE
Does BLOCKS update a subset of weights in the lookup table layer?

### ISSUE THREAD

**Issue by yang1fan2** [mila-udem/blocks#1056]
Hi

I found my embedding layer a little bit slow. My question is whether BLOCKS updates the whole weight matrix or a subset of weight matrix in the lookup table layer? Thank you so much if you could take time to answer this.

( http://deeplearning.net/software/theano/tutorial/faq_tutorial.html )

Sincerely,
Yifan

**Comment by dmitriy-serdyuk** [comment]
No, we are not doing it. And it might be not easy to implement.

If you'd like to have it in blocks, I recommend you to take a look at [GradientDescent class](https://github.com/mila-udem/blocks/blob/master/blocks/algorithms/__init__.py#L161). Probably, you'll have to inherit from it and process gradients wrt lookup matrices in a different way (like it is advised in the tutorial you linked).

**Comment by yang1fan2** [comment]
Thanks for help, I'll have a try

**Comment by dmitriy-serdyuk** [comment]
Another way is to consider [constant this matrix](https://github.com/mila-udem/blocks/blob/master/blocks/algorithms/__init__.py#L197), compute the updates manually, and provide to the algorithm [using this](https://github.com/mila-udem/blocks/blob/master/blocks/algorithms/__init__.py#L128).
