### ISSUE TITLE
By default, biases in convolutions are not shared across spatial locations

### ISSUE THREAD

**Issue by ddtm** [mila-udem/blocks#1072]
This doesn't line up well with the default behaviour in other popular frameworks (e.g. torch7, Caffe, [lasagne](http://lasagne.readthedocs.org/en/latest/modules/layers/conv.html#lasagne.layers.Conv1DLayer)).

I figured out that Blocks does things differently when I tried to load weights from a pretrained model (a standard one for image recognition) borrowed from lasagne Zoo.

**Comment by dwf** [comment]
Checked Keras too, [they don't even provide the option](https://github.com/fchollet/keras/blob/master/keras/layers/convolutional.py#L121). Tied biases only.

**Comment by dwf** [comment]
If the default is changed an email to `blocks-users` is definitely necessary as this will be a breaking change for some.

**Comment by davidbau** [comment]
+1 to change the default: I just ran into this also and was also surprised.

**Comment by dwf** [comment]
Either of you want to submit a pull request? Should be a simple matter of flipping the flag and changing the tests. (And pinging the mailing list, since this is a breaking change, which we don't shy away from but try to notify people about.)

**Comment by davidbau** [comment]
Submitted pull #1108.
