### ISSUE TITLE
VariableFilter should auto-instantiate a ComputationGraph if given a list or TensorVariable

### ISSUE THREAD

**Issue by dwf** [mila-udem/blocks#1080]
It's pretty unambiguous what I want if I pass either of these.

**Comment by rizar** [comment]
In which context can `VariableFilter` be given a list of `TensorVariable`?

**Comment by dwf** [comment]
What I mean is that if I say

`VariableFilter(...)([cost1, cost2])`

I pretty obviously mean

`VariableFilter(...)(ComputationGraph([cost1, cost2]))`.

A lot of the time I find myself creating a `ComputationGraph` *just* for the purpose of using the `VariableFilter`. It would be nice if `VariableFilter` would do it for you.

**Comment by rizar** [comment]
Got it, makes sense.

**Comment by dwf** [comment]
Um. Actually, the VariableFilter *always* expects a list (or at least iterable) of `TensorVariable`s. `ComputationGraph` implements `__iter__` so this is why `ComputationGraph`s are accepted in the first place.

In that case I propose a `graph=False` default keyword argument to `__call__`. If `True`, we call `ComputationGraph(variables)` on the first argument.

**Comment by rizar** [comment]
Hmm, actually, this seems to be a trivial syntax sugar that we could live
without. Adding `graph=True` to your `VariableFilter` call does not seem to
me that much simpler than creating a `ComputationGraph` before you call
`VariableFilter`. An explicit is better than implicit, they say.

**Comment by dwf** [comment]
When you're doing it multiple times per day, it adds up, believe me. Plus
it's an extra import.

**Comment by rizar** [comment]
I will not insist to hard on it, but I still think it is an example of code
bloat.

**Comment by dmitriy-serdyuk** [comment]
Would it solve the issue if we always [`pack`](https://github.com/mila-udem/blocks/blob/master/blocks/utils/__init__.py#L16) the input to the variable filter?

**Comment by dwf** [comment]
Looking back, I am not convinced this is such a good idea anymore.
