### ISSUE TITLE
Use six.wraps insted of functools.wraps

### ISSUE THREAD

**Issue by naicode** [mila-udem/blocks#1086]
#### What?
From python 3.2 onward `functools.wraps` adds a `__wrapped__` field to the wrapper.
`six.wraps` enables this functionality in python2

#### Why?
Having a way to refer to the wrapped function can be useful if you e.g. stack multiple
annotations and want to get the original function signature. (The function signature is,
for example used in the `recurrent` annotation to convert args to kwargs, so using
`recurrent` on a wrapped function *could* lead to problems if the parameters are not
passed in by name (but by index))

**Comment by dwf** [comment]
Feel free to send a PR.

**Comment by dmitriy-serdyuk** [comment]
It's also nice for documentation purposes, I had to do it in fuel mila-udem/fuel#346 .
