### ISSUE TITLE
Bidirectional class with prototype that includes Fork or Merge as children.

### ISSUE THREAD

**Issue by Beronx86** [mila-udem/blocks#1114]
I am writing a Bidirectional class with prototype that includes Fork or Merge as children. It seems that some operations are fused (theano optimization). So when constructing ComputeGraph, the `get_brick` function cannot get the Fork or Merge brick. It may because  the intermediate variables, such as Fork outputs, are fused and not in the graph variable list.  At last, multiply top brick are found. But in fact, there is only one top brick.

**Comment by dwf** [comment]
Fusion doesn't happen until compilation so I think it must be something else.
