### ISSUE TITLE
different learning rates in different modules.

### ISSUE THREAD

**Issue by Beronx86** [mila-udem/blocks#1122]
I am using an encoder-decoder framework. I want to use different learning rates in the encoder and decoder. Are there any suggestions?

**Comment by dwf** [comment]
1. use the `Selector` and/or `VariableFilter` to pull out lists of parameters for the encoder and decoder separately.
2. Use two `Restrict` step rules inside a `CompositeRule` to apply different base learning rules (e.g. ```python
CompositeRule([
    Restrict(Adam(learning_rate=learning_rate_enc), encoder_parameters),
    Restrict(Adam(learning_rate=learning_rate_dec), decoder_parameters)
])
```

The [mailing list](https://groups.google.com/forum/#!forum/blocks-users) is a better place for usage questions.
