### ISSUE TITLE
Initializable doesn't accept 'children' keyword argument (e.g. in 'Create your own brick' tutorial)

### ISSUE THREAD

**Issue by hsintone** [mila-udem/blocks#1135]
Running the code a the very end of the 'Create your own brick' tutorial[0] where you define the ParallelLinear2 class and create an instance of it produces the following error:

```
In [24]: parallel2 = ParallelLinear2(input_dim1, input_dim2, output_dim1,
    ...: ...                             output_dim2, weights_init=Constant(2))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
...
/blocks/bricks/interfaces.pyc in __init__(self, weights_init, biases_init, use_bias, seed, **kwargs)
    146     def __init__(self, weights_init=None, biases_init=None, use_bias=True,
    147                  seed=None, **kwargs):
--> 148         super(Initializable, self).__init__(**kwargs)
    149         self.weights_init = weights_init
    150         if self.has_biases:

TypeError: __init__() got an unexpected keyword argument 'children'
```

[0] http://blocks.readthedocs.io/en/latest/create_your_own_brick.html

**Comment by dmitriy-serdyuk** [comment]
It works fine for me. Can you provide more information? Which version of Python are you using?

**Comment by hsintone** [comment]
Sure. Here's some version information:
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
blocks 0.1.1: Mon Aug  1 17:28:18 2016
Theano 0.9.0.dev2: Mon Aug  1 17:28:18 2016
numpy 1.11.1: Mon Aug  1 17:28:18 2016

I noticed this when I was working on my own network with Initializable bricks. To debug I opened a new ipython console, imported the relevant bits (Initializable, Constant, application, Linear), pasted the tutorial code and got the same error.

Here's the full traceback that I for some reason trimmed down:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-15-79c92b7ad95f> in <module>()
      1 parallel2 = ParallelLinear2(input_dim1, input_dim2, output_dim1,
----> 2                             output_dim2, weights_init=Constant(2))

<ipython-input-6-5a527bf47970> in __init__(self, input_dim1, input_dim2, output_dim1, output_dim2, **kwargs)
      8         children = [self.linear1, self.linear2]
      9         kwargs.setdefault('children', []).extend(children)
---> 10         super(ParallelLinear2, self).__init__(**kwargs)
     11
     12     @application(inputs=['input1_', 'input2_'], outputs=['output1',

~/.local/lib/python2.7/site-packages/blocks/bricks/base.pyc in lazy_init(*args, **kwargs)
    833             for initialization_arg in initialization:
    834                 kwargs.setdefault(initialization_arg, NoneInitialization)
--> 835             return init(**kwargs)
    836         wraps(init)(lazy_init)
    837         return lazy_init

~/.local/lib/python2.7/site-packages/blocks/bricks/interfaces.pyc in __init__(self, weights_init, biases_init, use_bias, seed, **kwargs)
    146     def __init__(self, weights_init=None, biases_init=None, use_bias=True,
    147                  seed=None, **kwargs):
--> 148         super(Initializable, self).__init__(**kwargs)
    149         self.weights_init = weights_init
    150         if self.has_biases:

TypeError: __init__() got an unexpected keyword argument 'children'
```

Is there any other info I could provide?

**Comment by dmitriy-serdyuk** [comment]
You are using a very old version of blocks, try to update it.

**Comment by hsintone** [comment]
Hmm.. I just updated it. There might be some confusion with different python or pip installations. I'll investigate.

**Comment by hsintone** [comment]
Yeah, it works inside virtualenv, so somekind of mix-up with my installation. Sorry for the false report.

**Comment by kadir-gunel** [comment]
Hello, 
I am getting the same error with the latest blocks (0.2.0) and theano (0.9.0b1) in a virtualenv.
I am using python3.5.

Could you help please?

B.R.

**Comment by dwf** [comment]
Make sure you don't have multiple conflicting versions inside/outside the
virtualenv. Check `blocks.__file__`.
