### ISSUE TITLE
VisibleDeprecationWarning now results an error

### ISSUE THREAD

**Issue by SwordYork** [mila-udem/blocks#1179]
Hi,

After upgrading python to 3.5, the following warning results an error. I think it is better to change the type of [mask](https://github.com/mila-udem/blocks/blob/master/blocks/search.py#L275) or change `outputs = [list(output[:mask.sum()])` ([line 323](https://github.com/mila-udem/blocks/blob/master/blocks/search.py#L323)) to `outputs = [list(output[:int(mask.sum())])`.
I'm not sure which way is better.

> python3.4/site-packages/blocks/search.py:324: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
>   for output, mask in equizip(outputs, masks)]

Thanks.

**Comment by dmitriy-serdyuk** [comment]
Thank you! Could you make a PR? Perhaps, we should start testing with 3.5 version.
