### ISSUE TITLE
Sampling in recurrent function causes error

### ISSUE THREAD

**Issue by wenhuchen** [mila-udem/blocks#1182]
I found that whenever I use sampling in the recurrent-wrapped function,  error message like
"Input 0 of the graph (indices start from 0), used to compute Elemwise{identity}(a_initial_states_states[t-1]), was not provided" will be reported.
A very simple demo could produce this error, can anyone tell me what is wrong?

```
from blocks.bricks import Initializable, application
from blocks.bricks import recurrent
import theano.tensor as tensor
import numpy
from blocks.bricks import NDimensionalSoftmax
from theano.sandbox.rng_mrg import MRG_RandomStreams

class A(Initializable):
    def __init__(self, dim, **kwargs):
        super(A, self).__init__(**kwargs)
        self.dim = dim
        self.theano_rng = MRG_RandomStreams()
        self.softmax = NDimensionalSoftmax()
    
    @recurrent(sequences=['inputs'], states=['states'], outputs=['states', 'outputs'], contexts=[])
    def apply(self, inputs, states):
        new_states = inputs + states
        probs = self.softmax.apply(new_states)
        outputs = self.theano_rng.multinomial(pvals=probs)
        return new_states, outputs
    
    @application(outputs=['states'])
    def initial_states(self, batch_size, *args, **kwargs):
        return tensor.ones((batch_size, ))
    
    def get_dim(self, name):
        return self.dim

a = A(3)
a.initialize()
x = tensor.matrix('x')
y = a.apply(x)
y[0].eval({x: numpy.ones((2,3), dtype='float32')})
```

**Comment by dmitriy-serdyuk** [comment]
Just like in Theano you need to provide the updates to the function. You can extract all the updates using a `ComputationGraph`:
```python
from blocks.graph import ComputationGraph
cg = ComputationGraph(y)
func = theano.function([x], y, cg.updates)
func(numpy.ones((2,3), dtype='float32'))
```

**Comment by wenhuchen** [comment]
Thanks for your explanation, I do notice that the error can be eliminated by adding updates. But do you know what these updates represent? I can see it's a tuple like <random_variable, subtensor.0>, what does this update do?

**Comment by dmitriy-serdyuk** [comment]
It updates the state of the random number generator, see [here](http://deeplearning.net/software/theano/library/tensor/shared_randomstreams.html) and [here](http://deeplearning.net/software/theano/tutorial/examples.html#using-random-numbers).

**Comment by wenhuchen** [comment]
Thanks a lot, your answer is really helpful
