### ISSUE TITLE
python setup.py install can't work

### ISSUE THREAD

**Issue by weizier** [mila-udem/blocks#1193]
...
byte-compiling build\bdist.win-amd64\egg\tests\utils\test_imports.py to test_imports.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\tests\utils\test_utils.py to test_utils.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\tests\utils\__init__.py to __init__.cpython-36.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
installing scripts to build\bdist.win-amd64\egg\EGG-INFO\scripts
running install_scripts
running build_scripts
creating build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-3.6\blocks-continue -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying blocks.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying blocks.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying blocks.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying blocks.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying blocks.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying blocks.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
creating 'dist\blocks-0.2.0-py3.6.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing blocks-0.2.0-py3.6.egg
creating f:\anaconda3\lib\site-packages\blocks-0.2.0-py3.6.egg
Extracting blocks-0.2.0-py3.6.egg to f:\anaconda3\lib\site-packages
Adding blocks 0.2.0 to easy-install.pth file
Installing blocks-continue script to F:\Anaconda3\Scripts

Installed f:\anaconda3\lib\site-packages\blocks-0.2.0-py3.6.egg
Processing dependencies for blocks==0.2.0
Searching for fuel
Reading https://pypi.python.org/simple/fuel/
Downloading https://pypi.python.org/packages/16/c2/b5fb651c90e908f79769b7dd3643982b6a9b1bac9449b8ab16f72612d4f5/fuel-0.2.0.tar.gz#md5=48bf3267009f7a4285c101485321b87d
Best match: fuel 0.2.0
Processing fuel-0.2.0.tar.gz
Writing C:\Users\...\AppData\Local\Temp\easy_install-k8yigysa\fuel-0.2.0\setup.cfg
Running fuel-0.2.0\setup.py -q bdist_egg --dist-dir C:\Users\...\AppData\Local\Temp\easy_install-k8yigysa\fuel-0.2.0\egg-dist-tmp-spwjgkes
error: Setup script exited with error: [WinError 2] 系统找不到指定的文件。

**Comment by dmitriy-serdyuk** [comment]
This if a fuel issue: https://github.com/mila-udem/fuel/issues/397
