### ISSUE TITLE
More Aggregation Schemes: Min, Max, Concatenate

### ISSUE THREAD

**Issue by rizar** [mila-udem/blocks#129]
That would a nice exercise for a newcomer: to add a couple of new aggregation schemes in addition to existing ones. Would be very helpful for debugging purposes.

**Comment by Tejas-Khot** [comment]
@rizar I am a newcomer and looking at first solving such smaller issues to get better acquainted with how things work with blocks. Could you please tell me more on this one or point me to some relevant source. I could work on this then.

**Comment by rizar** [comment]
Sure!

The existing aggregation schemes are here: https://github.com/mila-udem/blocks/blob/master/blocks/monitoring/aggregation.py

I have just realized that we do not have a tutorial for aggregation schemes (shame to us), but perhaps [this line](https://github.com/mila-udem/blocks-examples/blob/master/reverse_words/__init__.py#L212) explains their purpose best.
