### ISSUE TITLE
Early Stopping

### ISSUE THREAD

**Issue by rizar** [mila-udem/blocks#327]
Blocks miss an early stopping extension. This involves figuring out the right time to stop and/or save the training process.

It could be done like that: an extension tracks the given quantity in the log and makes a record when (a) it has reached its minimum/maximum so far (b) when it thinks that no further improvement can be expected. In the case (b) the termination request can be written to the log. The record from the case (a) can be handled by another extension configured to do so.

Altogether it should look like that:

```python
MainLoop(...,
    extensions=[
        ..., 
        EarlyStopping("validation_cost"),
        SerializeMainLoop(path=path_for_the_best)
             .set_conditions() # we have to clear the default condition
             .add_condition(
            "after_epoch", OnRecord(EarlyStopping.BEST_SO_FAR)),
        ...
    ]
)
```

The `OnRecord` predicate is of course to be implemented but this is trivial.

**Comment by rizar** [comment]
There's not so much left here after #448, so I put CCW label.

**Comment by vikkamath** [comment]
Probably irrelevant for this issue, but what does 'CCW' stand for?

**Comment by dwf** [comment]
@rizar What precisely do you think is left to do?

**Comment by rizar** [comment]
An extension that decides when to stop. Implements one of these heuristic rules, smth like "if we did twice more iterations and did not get better, halt". I am not a specialist in these ones, perhaps it would make sense to implement the same one as in PyLearn2.

**Comment by dwf** [comment]
I didn't mean to close this, sorry.
