### ISSUE TITLE
Non 2d weight parameters

### ISSUE THREAD

**Issue by jbornschein** [mila-udem/blocks#366]
The LSTM class uses the WEIGHTS role for a 1d weight vector:

https://github.com/bartvm/blocks/blob/master/blocks/bricks/recurrent.py#L352

while some of the initialization objects only operate on 2d matrices. E.g. Identity and Orthogonal.

Currently the code will just crash when using such an initialization. I see two ways to approach this issue: a) A brick allocating 1d weight matrices has to ensure that the user can supply a different, suitable initialization method for those parameters, or b) all initialization classes meant for matrices should provide a reasonable 1d initialization. 

a) is already implemented because we can of course alter the initialization scheme for different parameters after object creation... but this issue should probably be mentioned in the LSTM documentation. Maybe the constructor should take an additional 'weights_1d_init' argument?

b) seems preferable from a 'things should just work' perspective. But maybe the user should better be aware of these parameters that don't fit the chosen initialization scheme?

**Comment by dwf** [comment]
I think the right thing here would be to generalize most of the
initializers to support 1d, except in the cases where it clearly doesn't
make sense.

**Comment by memimo** [comment]
Any update on this issue?
I think it makes sense to have different initialization scheme for transition matrix, and cells. And now that there is a  RecurrentStack, the default linear transformer might need different initialization.

**Comment by rizar** [comment]
Sure, we need more fine-grained initialization for recurrent bricks. A new more specific issue has just been created, #740. I suggest to move the discussion there and close this issue as a duplicate.  Do you agree?

**Comment by memimo** [comment]
Thx I was not aware of the 740.

**Comment by jbornschein** [comment]
Yes, close it. I wasn't even aware that this one is still open.
