### ISSUE TITLE
gated_activation should be an optional keyword argument of GatedRecurrent

### ISSUE THREAD

**Issue by bartvm** [mila-udem/blocks#416]
Right now the docstring suggests its optional, but it's actually a required argument in the signature.

**Comment by Tejas-Khot** [comment]
@bartvm As of today, the docstring does not say its optional. Is the issue closed or its something else you suggest ? Could you explain please.

**Comment by rizar** [comment]
The docstring does say that `None` can be passed, which in a way declares that the parameter is optional (although explicit declaration would be better). But other than that, the issue seems to be solved and I am closing it.
