### ISSUE TITLE
Merge Dump and Checkpoint into a single extension?

### ISSUE THREAD

**Issue by bartvm** [mila-udem/blocks#474]
This is more intended to be a long-term goal, but the custom pickler of `joblib` made me think that we could probably do something very similar as `joblib.dump` tha combiens the functionality of `Dump` and `Checkpoint`, which would remove a lot of duplicate functionality.

Just like `joblib` does we could intercept NumPy arrays and save them to disk instead of pickling them. The only functionality we need to add on top is giving those files a slightly more sensible name than `model.23423423.npy`. The same pickling class could give sensible errors for when unpicklable objects are encountered.

There are probably some details to iron out, but overall I think that on the mid/long-term this could be a very nice and clean solution to the duplicity we have right now with `Dump`, `Checkpoint` and a range of semi-informative pickling error messages.

**Comment by dwf** [comment]
+1

**Comment by rizar** [comment]
In fact `Checkpoint` and `Dump` can be merged even now, just adding a flag to `Checkpoint` making save `.npz` file as well should do the job. We should get rid of `LoadFromDump` - the rationale behind it was that we have to load the log after the algorithm as initialized, because algorithm would not be initialized when resuming training with an old log. Instead we should make algorithm initialization lazy and always called.

**Comment by bartvm** [comment]
That's more of a stop-gap solution though, because from what I understand you want to save everything twice? Both as a large pickle file, and then again separately as an `.npz` file. What I'm proposing is a single, more intelligent pickling solution that automatically saves any NumPy array in the object hierarchy separately.

There shouldn't be any need then for forcing parameters to have a unique path/name in the brick hierarchy. You basically save them to files with a name like `uniqueid.parameter_name.npy`. You'll only have to ensure that parameter names are unique in cases where you want to distribute the NumPy arrays separately or transfer/inspect them easily.

This actually comes back to #480, because although forcing uniqueness on the short-term makes sense, if we have this solution, I think we shouldn't enforce it. Its' a pain in the ass to make sure every variable has a unique name when you're not using bricks, so if we can handle serialization without it, we should.

**Comment by rizar** [comment]
> What I'm proposing is a single, more intelligent pickling solution that automatically saves any NumPy array in the object hierarchy separately.

But parameters are not numpy arrays, they are shared variables hosted on GPU. Do you think wil be able to save them as numpy arrays and in separate files and then load back at unpickling? 

As for name uniqueness, I never was a fan of this idea. It's pain in the ass, as you said.

**Comment by bartvm** [comment]
I'll ask @lamblin and @nouiz about the details. At the very least we can call `get_value` during the pickling process. This would mean we still duplicate the data, but at least we will be able to save the NumPy arrays to separate files, which is better than not having a backup at all when pickling fails.

If your parameters aren't named it will be hard to reconstruct the model from files `2323.W.npy`, 2525.W.npy`, `5242.W.npy`, etc. but that is up to the user then, to decide how safe they want to be. In most cases when they use bricks we will be able to give reasonable names to the parameters though, allowing people to reconstruct the model if unpickling fails for some reason.

**Comment by nouiz** [comment]
You can use joblib as a replacement of pickle. Mostly, it is pickle, but
same ndarray in separate file in a better format. Grep in pylearn2 about
this.

**Comment by bartvm** [comment]
I definitely want to reuse some of `joblib`'s code, but we can't use it directly, because we want to store some metadata with the `.npy` files (e.g. the name of the parameters). Joblib would just produce 10 files called `model_01.np`, ..., `model_10.npy`, without a way for us to tell which file belongs to which weight matrix.

In order to know what weight matrix the NumPy arrays belong to, we'll have to intercept the pickling of the (annotated) Theano shared variable, so we need to intervene in the pickling process earlier than Joblib does.

**Comment by bartvm** [comment]
The annotations are stored on the Theano shared variable. They would get pickled as part of the variable.

However, the reason we want to store the weights to separate files, is so that they can be shared, inspected, and stored for a long time, without needing to unpickle the Theano object at all. Unpickling can be problematic if you're trying to unpickle a GPU model on CPU, if the Theano versions are very different, the Python versions are different (2 vs. 3), and it generally can be slow/memory-intensive.

So what we would like to have is something that takes a Blocks-annotated Theano graph and saves the shared variables to something like `encoder.mlp.linear.W.npy`, `encoder.mlp.linear.b.npy`, etc.

**Comment by nouiz** [comment]
Ok. You can check at what joblib do and replicate that with a different
naming. I think that fit your need.

**Comment by bartvm** [comment]
@nouiz Last question! If we can replace `CudaNdarraySharedVariable` and `TensorSharedVariable` objects with a temporary object in the pickle file, and reconstruct them when unpickling, do we have all use cases covered? Or are there more types of shared variables out there?

Long story:

I guess `joblib` gets us close, but `joblib` intercepts the saving of `ndarray` objects, while we need to intercept `TensorSharedVariable` objects so that we can retrieve the annotation.

However, that means that at this point we need to extract the data from the `TensorSharedVariable` and save it ourselves. I guess we can either register a custom pickler function (like in https://github.com/Theano/Theano/pull/2339), or subclass `Pickler`. A new pickler class could have a `save` method like:

```python
def save(obj):
    if isinstance(obj, TensorSharedVariable):
        data = obj.get_value()
        # Uses Brick hierarchy > variable name > numbering scheme to get a name
        sensible_name = get_sensible_name(obj)
        np.save(data, sensible_name)  # Save the data separately
    return Pickler.save(self, obj)
```

This ends up saving the data twice. We might want to avoid that to save space/memory/time. We don't want to modify the original object (`obj`) though, and creating a copy would probably ruin the graph, so `joblib`'s approach of replacing the object with a temporary wrapper in the pickle file might be a good idea then. We'd need an unpickler which can cleverly reconstruct both `CudaNdarraySharedVariable`s and normal `TensorSharedVariable`s in that case. (And we probably want to keep this optional, since it does make it impossible to unpickle the main loop without the custom unpickler).

**Comment by bartvm** [comment]
By the way, CC @dmitriy-serdyuk

**Comment by nouiz** [comment]
I think requesting that the unpickler is available is fine.

Theano already have pickler/unpickler for theano/sandbox/cuda/type.py for
CudaNdarray object. You could use the same for CudaNdarraySharedVariable
and TensorSharedVariable.

I do not know about the multiple copy of the data in memory.

There is other shared variable in theano. One for the new GPU back-end, for
sparse variable for typed list, ... But there isn't that many.

How exactly are stored the annocation? In shared_var.tag.* ?

**Comment by bartvm** [comment]
The annotations are stored in `.tag`, yes. In there is a reference to the "brick" that created the variable. Each brick has parents, so we can construct a path of bricks all the way to the root, which allows us to create a name for the parameter that looks something like `/encoder/mlp/linear.W`.

What is the container that all these shared variables store their data in (i.e. what is `type(obj.container.storage[0])`? I assume that for most of them its `ndarray`, but I'm not sure about the GPU shared variables? I'm guessing they contain some reference to data on the GPU instead? Otherwise we could make use of pickle's recursive structure and do something like:

```python
self.sensible_name = None

def save(self, obj):
    if isinstance(obj, TensorSharedVariable):
        self.sensible_name = get_sensible_name(obj)
        
    if isinstance(obj, numpy.ndarray) and self.sensible_name:
        # We're currently saving a shared variable
        # so we use joblib's approach and replace the NumPy array
        # with a wrapper and save the data to a file instead
        obj = NumpyWrapper(load_from=sensible_name + '.npy')
        numpy.save(obj, sensible_name + 'npy')
        self.sensible_name = None
    return Pickler.save(self, obj)

def load(self, obj):
    if isinstance(obj, NumpyWrapper):
        return numpy.load(obj.load_from)
```

That would stop us from having to write a custom pickler/unpickler pair for each kind of shared variable. It only works as long as each shared variable contains exactly one reference to a NumPy array in its object hierarchy though. I'm not sure how robust that is.

**Comment by lamblin** [comment]
I can also think of `RandomStateSharedVariable`, which is used for variables containing a NumPy `RandomState`. They are technically shared, but not what is usually considered as parameters of a model.

**Comment by bartvm** [comment]
Right. For `RandomStateSharedVariable` we can just do `and not isinstance(obj RandomStateSharedVariable)`, but it's more problematic for MRG RNG states I guess, because they're vanilla `TensorSharedVariable` objects right? We've ran into that problem with Blocks before. It could probably be fixed easily by creating a new subclass, or even by just adding a `._is_RNG` attribute that Blocks can check for, but it needs to be done in Theano.

I'm still a bit confused about the details of (shared) variables on GPU: Custom picklers are registered for in `sandbox/cuda/type.py` for `CudaNdarray` only. Does this mean that `type(shared_cuda_array.container.storage[0])` is `CudaNdarray` (where `type(shared_cuda_array)` is `CudaNdarraySharedVariable`? Are there other possible container types e.g. `GPUArray`? Is there a custom pickler for the new GPU-backend?

**Comment by lamblin** [comment]
It makes sense to tag these matrices as random states. One way to do it could be to add a weak reference to the `MRG_RandomStreams` that created them.
I opened https://github.com/Theano/Theano/issues/2668 for that.

**Comment by dmitriy-serdyuk** [comment]
> We should get rid of LoadFromDump - the rationale behind it was that we have to load the log after the algorithm as initialized, because algorithm would not be initialized when resuming training with an old log.

I don't completely agree here. `LoadFromDump` is a nice tool to make minor changes in your script and resume training.

**Comment by rizar** [comment]
Okay, thanks for letting us know that somebody is actually using it. I do not say that it's useless, I don't like that is is an extensions and would be something like that:

```python
main_loop = MainLoop(...)
# Loads parameters, log and iteration state into the main loop.
load_from_dump(dump_path, main_loop)
main_loop.run()
```

I find it clearer, but this can not currently be done for the reason that `algorithm` would not be initialized (it's initialized only if there is no `_training_started` flag in the log.

**Comment by rizar** [comment]
That has already happened.
