### ISSUE TITLE
Inconsistent usage of `params` and `parameters`

### ISSUE THREAD

**Issue by bartvm** [mila-udem/blocks#488]
We have `Brick.params`, `Selector.get_params`, `Model.get_params` and `DifferentiableCostMinimizer.params`, but on the other hand we have `ComputationGraph.parameters` and `dump_parameters`.

I think we should move to `parameters` in all cases, considering the general policy of preferring full names whenever they're not extraordinarily long (which I guess is the case here). Either way, we need to be consistent.

**Comment by rizar** [comment]
Sounds reasonable.

**Comment by EderSantana** [comment]
There is also `role.{WEIGHT, BIAS}` but `{weights,biases}_init`

**Comment by dwf** [comment]
This just got changed, and apparently we missed the
weights_init/biases_init arguments. I'd be all for changing it
eventually.

**Comment by bartvm** [comment]
Yeah, @mducoffe mentioned this in https://github.com/bartvm/blocks/pull/449#issue-60671600 too, and I think we should just be consistent and change all of them then.

**Comment by bouthilx** [comment]
We assigned the ticket for CCW this week. Do we all agree on using ```parameters``` rather than ```params```?

**Comment by vikkamath** [comment]
Shouldn't this be closed?

**Comment by bouthilx** [comment]
Lets wait for travis tests to pass before we close.
