### ISSUE TITLE
Various small things in ComputationGraph.replace 

### ISSUE THREAD

**Issue by rizar** [mila-udem/blocks#526]
- print a warning if the user tries to replace an auxiliary variables

- print a warning if the user tries to replace a variable that is not contained in the graph

- get rid of the topological sort and use already sorted `self.variables` instead

Makes an beginner-level CCW issue, I guess.

**Comment by bouthilx** [comment]
@rizar Why not raising an error when the variable is not contained in the graph?

**Comment by mohammadpz** [comment]
@bouthilx , Could you please take a look at my PR?

**Comment by rizar** [comment]
@bouthilx , perhaps an error would make more sense indeed.

**Comment by bouthilx** [comment]
@rizar @dmitriy-serdyuk  Can you close the issue please. :)

**Comment by rizar** [comment]
Sure, thanks!

I would really like to give your merge rights, but I don't have rights to give rights, unfortunately :(

**Comment by lamblin** [comment]
I added @bouthilx as an admin and @rizar as an owner.
