### ISSUE TITLE
Bricks loaded from pickle ignores default_seed

### ISSUE THREAD

**Issue by udibr** [mila-udem/blocks#548]
When you load from a pickle a model containing Bricks that were initialized from default_seed (Random, Initializable)
the loaded bricks are loaded with their past seed setup. Currently there is no clean way to reset the seed_default. This is needed for example if I want to generate different samples from a generative model using different default_seed values.

My current hack is to do the following after loading the model:
    del brick._theano_rng
    del brick._theano_seed
    brick.seed_rng = np.random.RandomState(config.default_seed)

It would be nice if there was a tool to perform this operation on all bricks

**Comment by bartvm** [comment]
I'm not sure I understand the problem exactly. I can see that `seed_rng` is a class attribute, so it's true that this will be re-initialized, and `seed_rng` will be reset after unpickling.

However, before pickling the `_theano_rng` attribute should already have been created, and its state should be pickled and after unloading it should be in exactly the same state. That is expected behaviour. Sampling from any RNG should thus give you new random samples? Is that not what you want?

**Comment by udibr** [comment]
Sorry for being unclear, in many cases you do want the brick to continue from exactly the same state in which it was when pickled and indeed this is what the current code provides.
However, in other cases you do want to reset the random process inorder to get different random results on repeated runs that are all starting from the same pickle. So I am hopping for something like a reset_seed method which will propgate to all bricks. I would expect that changing the default_seed would have done that but this does not happened because the state of the random process is already fixed by the loaded pickle from the time in which the pickle was created.

My hack is not nice because I am modifing attributes that are supposed to be hidden (starts with an underline)

**Comment by bartvm** [comment]
I see. But in your case, it should only work when you reset `.seed_rng`, and then rebuild the entire computation graph from the bricks again, right? Editing the brick won't edit the computation graph directly.

I'm inclined to say that the correct solution to your problem would be to figure out how to reset the state of an RNG in Theano. It should be a matter of re-initialization the state (which is just a shared variable), but I'm not sure if there's an easy way to do that.

@lamblin @nouiz Do either of you know if there is an easy way to reset an RNG (MRG RNG in particular) to a particular state, given a seed?

**Comment by udibr** [comment]
you are right! I suggest to close this issue if it is OK with you (although in general it is a good point to solve.) There is no easy way of modifing the Theano graph once it is built. My hack (accidently) worked only because I was calling a method of a preloaded brick that built a new graph, that was not built before. A better solution is to take out the method from the brick.

**Comment by lamblin** [comment]
With a `shared_randomstreams.RandomStreams`, you can reset all the shared random states that were created from it, via the `seed` method, but there is no way of resetting only the state of one given random variable without having recorded the initial state or seed explicitly.
For `MRG_RandomStreams`, that feature is currently missing, but should not be too hard to implement following the implementation in `RandomStreams.

**Comment by bartvm** [comment]
Isn't the initial seed stored in `RandomStreams.default_instance_seed`? I tried the `seed` method earlier today, but that didn't work for me:

```python
In [14]: rng = RandomStreams(2)

In [15]: rng.normal((1,)).eval()
Out[15]: array([-2.65042472], dtype=float32)

In [16]: rng.seed(2)

In [17]: rng.normal((1,)).eval()
Out[17]: array([-0.38396206], dtype=float32)
```

**Comment by lamblin** [comment]
Oh, but by calling `rng.normal` again, you create a new random variable with its own state. If you use the same variable, it will be reset:
```python
In [4]: u1 = rng.normal((1,))

In [5]: u1.eval()
Out[5]: array([-2.65042475])

In [6]: u1.eval()
Out[6]: array([ 0.68392734])

In [7]: rng.seed()

In [8]: u1.eval()
Out[8]: array([-2.65042475])

In [9]: u1.eval()
Out[9]: array([ 0.68392734])
```

**Comment by dwf** [comment]
@udibr @bartvm is this still relevant?

**Comment by bartvm** [comment]
Nope, I think the conclusion was that if @udibr wants to load his model and continue training/sampling with different random seeds he needs to change the state on the Theano random variables directly (using the `seed` method as mentioned by @lamblin), so there's nothing to be done in Blocks as far as I can tell (besides maybe adding this to documentation somewhere?)
