### ISSUE TITLE
Trainable Initial State for Recurrent Bricks

### ISSUE THREAD

**Issue by rizar** [mila-udem/blocks#594]
It is very easy to modify `SimpleRecurrent`, `GatedRecurrent` and `LSTM` to make their initial states trainable. It gives small but consistent gain in my application. In general I think that zero hidden states might be dangerous.

What you do guys think? Should we implement that and makes the new Blocks default?

**Comment by bartvm** [comment]
Yes, I think that training the initial state is the sensible thing to do in most applications.

**Comment by dwf** [comment]
Sounds reasonable to me.

**Comment by rizar** [comment]
Nice that you like this plan guys. I will implement in the nearest future then.

**Comment by dwf** [comment]
I think this was resolved by #600, @rizar please reopen if I'm incorrect.
