### ISSUE TITLE
"Creating a Brick" tutorial

### ISSUE THREAD

**Issue by dwf** [mila-udem/blocks#611]
Walking through my second or so time attempting to create a custom brick, I think it would be a good idea to have a "custom brick" tutorial, in the same spirit as the Theano tutorials that walk you through the creation of a custom op (albeit more high-level).

**Comment by bouthilx** [comment]
+1 :)

**Comment by dmitriy-serdyuk** [comment]
@adbrebs , this is your CCW ticket.
