### ISSUE TITLE
Sigmoid -> Logistic

### ISSUE THREAD

**Issue by dwf** [mila-udem/blocks#617]
The `Sigmoid` brick should really be named `Logistic`.

"Sigmoid" simply means "S-shaped" ([dictionary](http://dictionary.reference.com/browse/sigmoid?s=t), [Wikipedia](https://en.wikipedia.org/wiki/Sigmoid_function)).

**Comment by Thrandis** [comment]
Well, Logiscic seems to be the most general case:
http://en.wikipedia.org/wiki/Logistic_function
But what is used in neural networks is a sigmoid, a special case of the logistic function:
http://en.wikipedia.org/wiki/Sigmoid_function

**Comment by dwf** [comment]
Both of the links you pointed at seem to say the exact opposite of what you
stated. Sigmoid is a general term, encompassing functions like hyperbolic
tangent and probit. Logistic refers to y=1/(1+e^-x).

**Comment by Thrandis** [comment]
I understand it like this : 
logistic : y = L / (1 + e^(-k*(x-x_0)))
A special case of it is : y = 1 / (1 + e^-x), which is often called the sigmoid function.

Anyways, since is that it is called like this in Theano, pylearn2, Lasagne and Torch7, it seems to be a good idea to stick with the name sigmoid.

**Comment by dwf** [comment]
I think in this case that at least 2 of the other packages were cargo-culting Theano, and so Theano being imprecise caused others to be imprecise. To wit, from the "sigmoid function" article,

> Often, *sigmoid function* refers to the special case of the *logistic function* shown in the first figure and defined by the formula S(t) = 1/(1 + e^-t)

The scaled-shifted variant is not really anything I've seen referred to as the logistic, e.g. see [equation 3 from this 1995 tutorial paper](http://ftp.cs.nyu.edu/~yann/2004s-G22-3033-014/diglib/jordan_logistic.ps). Though the role of 'x0' and 'k' would be rolled into a preceding linear layer anyway.

**Comment by bartvm** [comment]
+1 That *Logistic* really is the correct name for this brick.
