### ISSUE TITLE
Creating a multilayer Jordan network

### ISSUE THREAD

**Issue by logloglog** [mila-udem/blocks#623]
Is it possible to create an RNN in blocks which has multiple hidden layers? I'm interested in being able to set the amount of hidden layers via code, so that I could have a Jordan network that looks (for example) like this:
```
   in1->|       Input     |    |              |           |        |
   in2->| (weights*inputs)| -> | hidden layer | -> ... -> | Output | ----> out1
|- r1 ->|        \|/      | -> |      1       | -> ... -> |        | --|---> out2
||-r2 ->| activation fn   |    |              |           |        |   |  |
||_____________________________________________________________________|  |
|_________________________________________________________________________|
```
I am *not* interested in feedback from hidden layers.
Basically, I was wondering if it's possible to add layers to an RNN out of the box, or is some code hacking needed to get this type of feedback?

**Comment by rizar** [comment]
Sorry for delay with the answer!

I am not sure I understand what you mean, but if you want to build a deep RNN e.g. like [here](http://www.cs.toronto.edu/~graves/icassp_2013.pdf), then the respective component is currently missing in Blocks. There is a ticket for implementation of this functionality, #46.

**Comment by logloglog** [comment]
Hello, no problem, thanks for the answer.
I'm looking for something like a deep RNN, yes. Basically, I would like to add an arbitrary number of hidden layers and be able to route data between any layer, so for example to have feedback from the output to the input, or from any hidden layer to the output.

**Comment by rizar** [comment]
Feedback from output to the input sounds not clear for me. From any hidden layer to the outputs means skip-connections, which is indeed sometimes done. However, a basic deep RNN, in which a layer new state is computed from its previous state and the new state of the layer below, would be the priority for Blocks and also not difficult to implement.

**Comment by logloglog** [comment]
I don't mean skipping. Feedback would just be taking the output of one layer and having it travel back "up" the chain. If we can have state/context units that effectively work as a delay/memory, it shouldn't make a difference if they connect the output to the input or a hidden layer to a hidden layer.

**Comment by rizar** [comment]
I am sorry, I am still not following you. Maybe you should try equations?

Even though I do not understand what exactly you need, I think you would require to build a new brick and use the `@recurrent` decorator for its main application method. :)

**Comment by logloglog2** [comment]
What's there not to follow?
Neural networks produce output. Output is taken as part of the input for the nth iteration down the road. This is called feedback. There's a whole article on Wikipedia, complete with illustrations.
https://en.wikipedia.org/wiki/Recurrent_neural_network

**Comment by rizar** [comment]
I know what feedback is. I do not understand what do you call Jordan network. Although it is mentioned on Wikipedia, this term seems not to be widespread.

If you want  a recurrent network with feedback, the `SequenceGenerator` from [here](https://github.com/mila-udem/blocks/blob/master/blocks/bricks/sequence_generators.py#L804) might be what you need. Only feedback from the previous step is supported. An example of modelling a markov chain with such a network can be found [here](https://github.com/mila-udem/blocks/blob/stable/examples/markov_chain/main.py).
