### ISSUE TITLE
cant run more than one target with the same cost in a single network

### ISSUE THREAD

**Issue by udibr** [mila-udem/blocks#645]
It is common to have a network that tries to optimize multiple targets at the same time.
For example, an autoencoder that also optimize a classifier.

However, if for example I build a cost function which contains multiple `BinaryCrossEntropy`
I get the error message

    ValueError: top bricks with the same name: binarycrossentropy

**Comment by rizar** [comment]
As the message suggests, you should change names of your `BinaryCrossEntropy` bricks to make all of them different, e.g.

```python
cost  = BinaryCrossEntropy(..., name='main_cost') + BinaryCrossEntropy(..., name='auxiliary_cost')
```

**Comment by dwf** [comment]
To add to what Dima said, are you trying to optimize multiple binary
targets? A single BinaryCrossEntropy brick should be able to do
vector-valued targets.
