### ISSUE TITLE
Add documentation on what a request iterator can return

### ISSUE THREAD

**Issue by dwf** [mila-udem/blocks#648]
Seems like integers or lists of integers, but I couldn't find this written down anywhere.

**Comment by dwf** [comment]
Should slice objects be supported?

**Comment by bartvm** [comment]
The reason we got rid of slices at one one is because it was leading to
silent errors (a slice outside of the boundaries just returns an empty
list).

We could/should support slices (might even be faster for HDF5?), but I
would make it a non-default option.

**Comment by dwf** [comment]
Almost certainly faster for HDF5.

**Comment by dwf** [comment]
... this should be a ticket on Fuel, d'oh.
