### ISSUE TITLE
Option to disable dumping the iteration state

### ISSUE THREAD

**Issue by memimo** [mila-udem/blocks#660]
If the dataset is large (e.g. 1e06) pickling fails.

**Comment by rizar** [comment]
Please, be more specific. What dataset do you use? Fuel datasets generally do not dump the actual data when pickled.

**Comment by memimo** [comment]
It's a custom indexable dataset, memory wise is not that big, it's just have many small examples. 
[This is the line](https://github.com/mila-udem/blocks/blob/master/blocks/dump.py#L134) that causes the pickling error.

**Comment by rizar** [comment]
Here is what you need: https://github.com/mila-udem/fuel/blob/master/fuel/utils.py#L28

The idea is that data should be loaded after unpickling only when requested, in the `load` method.

**Comment by memimo** [comment]
i see, yeah this will solve it, thanks!
