### ISSUE TITLE
Give ConvolutionalSequence a saner default for border_mode

### ISSUE THREAD

**Issue by vdumoulin** [mila-udem/blocks#681]
It forces all convolutional layers it wraps to have the same border mode, which is a nightmare to fix if you happen to have layers with 'full' border mode and others with 'valid' border mode.

**Comment by vdumoulin** [comment]
After giving it some thought, I can see where it can be useful to set one global border mode for all layers, but the current implementation gives the user no choice.

A better alternative IMHO would be to have `border_mode` default to `None`, in which case `border_mode` isn't pushed down the list of layers. If `border_mode` is something other than `None`, then `border_mode` will get pushed down to all layers.

**Comment by bartvm** [comment]
But this is the way it's done in all of blocks, like with weights_init. The
idea is that you first set a global one, then call
"push_allocation_config", then change the individual child bricks.

**Comment by vdumoulin** [comment]
`weights_init`'s value doesn't have any side effect. Changing the value of `border_mode` causes the output dimensions to change, which also changes the next convolutional brick's `num_channels` and `image_size` properties.

**Comment by bartvm** [comment]
Ah, right... I guess that's a case we never had before, where it's impossible to configure the children separately. In that case your solution sounds good.

**Comment by dwf** [comment]
Shouldn't change `num_channels`, should it? Though I agree, convolution is the main place where pylearn2's automagical method was desirable if not indispensable.

**Comment by vdumoulin** [comment]
To make it clearer to other people reading this issue, here's an example:

``` python
from blocks.bricks.conv import ConvolutionalActivation, ConvolutionalSequence
from blocks.bricks import Rectifier
from blocks.initialization import IsotropicGaussian, Constant

convnet = ConvolutionalSequence(
    layers=[
        ConvolutionalActivation(
            activation=Rectifier().apply,
            filter_size=(5, 5),
            border_mode='full',
            num_filters=16,
            name='layer_1'),
        ConvolutionalActivation(
            activation=Rectifier().apply,
            filter_size=(1, 1),
            num_filters=16,
            name='layer_2'),
        ConvolutionalActivation(
            activation=Rectifier().apply,
            filter_size=(1, 1),
            num_filters=16,
            name='layer_3')
    ],
    num_channels=8,
    image_size=(28, 28),
    weights_init=IsotropicGaussian(0.01),
    biases_init=Constant(0),
    name='convnet')
```

Now, here's what you need to do to configure the convnet back to what you'd expect:

``` python
convnet.push_allocation_config()
convnet.layers[0].border_mode = 'full'
convnet.layers[0].push_allocation_config()
convnet.layers[1].num_channels = convnet.layers[0].get_dim('output')[0]
convnet.layers[1].image_size = convnet.layers[0].get_dim('output')[1:]
convnet.layers[1].push_allocation_config()
convnet.layers[2].num_channels = convnet.layers[1].get_dim('output')[0]
convnet.layers[2].image_size = convnet.layers[1].get_dim('output')[1:]
convnet.layers[2].push_allocation_config()
```

All of this only to set `convnet.layers[0].border_mode` to `full`.
```

**Comment by dwf** [comment]
I just ran into this myself. Muy annoying.

**Comment by dwf** [comment]
@vdumoulin hopefully you saw that this was fixed.
