### ISSUE TITLE
bug in decorator to Parallel.__init__

### ISSUE THREAD

**Issue by udibr** [mila-udem/blocks#698]
The line:
https://github.com/mila-udem/blocks/blob/master/blocks/bricks/parallel.py#L59
    @lazy(allocation=['input_dims', 'input_dims', 'output_dims'])
should be
    @lazy(allocation=['input_names', 'input_dims', 'output_dims'])

**Comment by bartvm** [comment]
e4bf12ca245676e76d9b06e2e6a986d854a6d90a
