### ISSUE TITLE
Making forward path of a deep vision(video) model( sort of recurrent neural network model)

### ISSUE THREAD

**Issue by haanvid** [mila-udem/blocks#713]
Currently, using Theano, I worked on a model that has both spatial and temporal processing mechanisms (sort of recurrent network model).
I give videos as an input to the model. 
And the input is a 5-dimensional tensor: (time steps:100, mini-batches: 40, channels: 3, height: 100, width: 100)
It seems that there is a problem on handling time domain in theano.

For the making a forward path on the model, I first tried using 'scan' function which is in the Theano's library, but it took too much time.
I found out that overhead of scan is huge, and that takes the most of the computation time.

So, I also tried 'unrolled loop' version to do the forward path. 
It was much faster than using 'scan', and worked fine in small number of time steps.
But, when the number of time steps for the video was increased, the Theano's graph got exceedingly large and error message was
given as follows:

"RuntimeError: maximum recursion depth exceeded in cmp" 

So, I looked for other alternative methods to make the forward path for the model training.
And found that 'Blocks' library (http://blocks.readthedocs.org/en/latest/rnn.html) doesn't use 'scan' function of Theano :

"Notice how no call to theano.scan() is being made. This is because the implementation of apply is responsible for computing one time step of the recurrent application of the brick. It takes states at time t−1 and inputs at time t and produces the output for time t. The rest is all handled by the @recurrent decorator behind the scenes."

Will 'Blocks' solve the problem for me?
Because it uses different method for making the forward path?

**Comment by dwf** [comment]
[Scan is still used.](https://github.com/mila-udem/blocks/blob/master/blocks/bricks/recurrent.py#L210) Inside the `recurrent` decorator. It's possible that keeping as much of the graph as possible outside scan will solve some of your overhead issues.

**Comment by haanvid** [comment]
Oh, thanks I'll look into it

**Comment by rizar** [comment]
Properly used `theano.scan` does not introduce too much of overhead. I recommend you to pay attention to `non_sequences` argument and use it as much as possible to completely isolate your scan computations from the rest of the graph. This will also positively influence on the compile time.

**Comment by haanvid** [comment]
Thanks!
