### ISSUE TITLE
Refactor Linear and Convolutional to allow messing with the parameters in subclasses

### ISSUE THREAD

**Issue by dwf** [mila-udem/blocks#723]
Case in point: a brick that always masks its weights with a certain pattern. Reusing the code in the apply method is not easy because it is using the object attributes for the parameters.

I think the easiest thing to do is put the meat of the operation in a private static method that takes parameters and input as arguments, that gets called by the apply method. A subclasser can either call super() to get the apply of the superclass (if they want to do some post-processing) or call the static method themselves with whatever arguments they like (if they want to do some pre-processing of the parameters).

* call super()

@rizar Curious as to your thoughts.

**Comment by rizar** [comment]
At early stages of Blocks development we planned that direct manipulation of the `params` array would be used for such purposes. E.g. `brick.params[1] = brick.params[0].T` can tie the weights between the first two layers. Would that work for you?

**Comment by dwf** [comment]
I guess I don't totally understand how the `VariableFilter` works. Would it still find the original shared variables? Would `GradientDescent` work as before in such a situation? It's not clear to me. What would get returned if I called `VariableFilter(roles=[PARAMETER])(cg)`, the  masked version or the real shared variables? It's not clear to me.

**Comment by dwf** [comment]
So  I tried what you suggested, I think:

```
class Foo(Linear):
    ...
    def _initialize(self):
        super(Foo, self)._initialize()
        self.params[0] = tensor.triu(self.params[0], k=1)

    @application(inputs=['input_'], outputs=['output'])
    def apply(self, input_):
        linear = super(Foo, self).apply(input_)
        ...
        ...
```

You would think that this would prevent the model being learned with this brick from getting any gradient on the weights in the lower triangle of this matrix. You would be wrong.

![](https://i.imgur.com/o6cM817.png)

Any idea why?

**Comment by rizar** [comment]
To your first post: the parameter substitutions will be tagged as parameters. The tagging happens upon assignment to a `params` item, [see here](https://github.com/mila-udem/blocks/blob/master/blocks/bricks/base.py#L44). You will find the substitutions if you try `VariableFilter(roles=[PARAMETER])(cg)`. The `cg.parameters` call will have however not return them, since it only returns shared variables tagged as parameters. 

`GradientDescent` will work if you provide it with the right `parameters` argument :) The are always two options for that: `cg.parameters` and `cg.shared_variables`. The first differs from the second by filtering only parameter-tagged variables.

In general, things quickly start getting vague when one starts replacing parameters.

I have no idea why your example doesn't work as expected. Debugprint?

I am afraid moving out logic in static methods is a bit of an overkill. However, parameter replacement can be supported  by the application methods, e.g. `brick.apply(x, replace_params=[...])` can temporarily substitute  the `brick.params` array, forcing the application method `apply` to use `replace_params`.

**Comment by dwf** [comment]
On Jun 20, 2015 6:06 AM, "Dmitry Bogdanov" <notifications@github.com> wrote:
>
> To your first post: the parameter substitutions will be tagged as
parameters. The tagging happens upon assignment to a params item, see here.
You will find the substitutions if you try
VariableFilter(roles=[PARAMETER])(cg). The cg.parameters call will have
however not return them, since it only returns shared variables tagged as
parameters.
>
> GradientDescent will work if you provide it with the right parameters
argument :) The are always two options for that: cg.parameters and
cg.shared_variables. The first differs from the second by filtering only
parameter-tagged variables.

So there is no sane way of specifying a parameter substitution that is a
function of an original shared variable, and having it work without
modifying things in at least two places. Not ideal.

> In general, things quickly start getting vague when one starts replacing
parameters.
>
> I have no idea why your example doesn't work as expected. Debugprint?
>
> I am afraid moving out logic in static methods is a bit of an overkill.
However, parameter replacement can be supported by the application methods,
e.g. brick.apply(x, replace_params=[...]) can temporarily substitute the
brick.params array, forcing the application method apply to use
replace_params.

Are you saying this is already implemented or you're suggesting it as the
way to support this?

**Comment by rizar** [comment]
> So there is no sane way of specifying a parameter substitution that is a
function of an original shared variable, and having it work without
modifying things in at least two places. Not ideal.

Definitely not ideal. But to be honest, I don't know what is the ideal behaviour. What should be tagged as parameter: the original shared variable and/or the replacement which is a function of it? Your thoughts?

> Are you saying this is already implemented or you're suggesting it as the
way to support this?

I just threw an idea in the air.

**Comment by dwf** [comment]
On Sat, Jun 20, 2015 at 10:13 AM, Dmitry Bogdanov <notifications@github.com>
wrote:
>
> Definitely not ideal. But to be honest, I don't know what is the ideal
> behaviour. What should be tagged as parameter: the original shared variable
> and/or the replacement which is a function of it? Your thoughts?
>
 I would think the thing that is actually to be acted on by the learning
algorithm ought to be called the parameter.

One thought: we already define properties in Linear (and could do the same
in Convolutional) for self.W and self.b. If we used the properties inside
the apply method, rather than unpacking the params list every time, this
has two desirable side effects:

* You can call Linear or Convolutional's apply method even if your subclass
has more than 2 parameters in its params list.
* You can override the property to perform substitution in the subclass.

Thoughts?

**Comment by rizar** [comment]
>  I would think the thing that is actually to be acted on by the learning algorithm ought to be called the parameter.

That sounds reasonable, but arguably there should be also a way to filter out "semantic" parameters, that is those Theano variables that replace the shared variable parameters. And this is basically what the current `PARAMETER` role stands for: the variables that semantically are parameters (that is belong to one of `params` lists) have it.

I like your refactoring proposal. We should discourage direct references to the `params` array in application methods for reusability reasons.

**Comment by dwf** [comment]
#1009 more or less resolves this.
