### ISSUE TITLE
DifferentiableCostMinimizer is a lame duck

### ISSUE THREAD

**Issue by dwf** [mila-udem/blocks#735]
Perhaps I am missing something, but it does not look like DifferentiableCostMinimizer does very much (it neither differentiates nor minimizes), nor do we have any subclasses other than GradientDescent. Is there an argument for pushing functionality found there up to TrainingAlgorithm and/or down to GradientDescent?

**Comment by dwf** [comment]
In fact, I think I'd propose a refactoring of what's currently there that makes more sense to me for supporting descent methods that don't involve explicit gradients (the biologically plausible stuff, as well as things like EM where you might derive a closed form update).

* An `UpdatesAlgorithm` (or `SimpleAlgorithm`, or `BasicAlgorithm`, or `StepAlgorithm`, or something) that takes a set of raw updates and a step rule and applies them, no involvement of gradient machinery;
* `GradientDescent` inherits from this and adds the ability to derive updates from a cost. The current `gradients` argument could go away, one could simply use the base class.

**Comment by rizar** [comment]
Good point, `DifferentiableCostMinimizer` is indeed useless. The original idea behind was that this base class for all cases when the minimized cost is a Theano variable, as opposed to let's say word error rate and BLUE score. But seems like you can't go too far with this assumption...

I would go for `TrainingAlgorithm` as the basic interface, `UpdatesAlgorithm` as the interface for all algorithms that use Theano functions and the current `GradientDescent`.
