### ISSUE TITLE
Adam default learning rate does not match documentation

### ISSUE THREAD

**Issue by youralien** [mila-udem/blocks#767]
The documentation reads 0.0002 (which I believe is correct, according to the paper).
See line 718:
https://github.com/mila-udem/blocks/blob/master/blocks/algorithms/__init__.py#L718

However, the default learning rate is incorrectly set to 0.002
See line 731:
https://github.com/mila-udem/blocks/blob/master/blocks/algorithms/__init__.py#L731

**Comment by bartvm** [comment]
Right, we changed that at one point by recommendation of Kingma, but he later came back on his recommendation, so it should be changed back to 0.0003 or 0.0002.

**Comment by dwf** [comment]
Think this has been adequately addressed.
