### ISSUE TITLE
Instead of `named_copy` add a `name` argument to `v.copy()` in Theano

### ISSUE THREAD

**Issue by rizar** [mila-udem/blocks#784]

**Comment by lamblin** [comment]
`v.copy()` is just `tensor.Elemwise(identity)(v)`, so while it would be possible to add such a parameter, it would be strange not to have it for other elemwise operations (not to mention other Ops).
I'm not opposed to that, but we'll have to discuss it.

**Comment by lamblin** [comment]
Summary of an IRL discussion with @nouiz: it is strange to have `.copy()` only defined for tensors, and use an elemwise, rather than returning a `ViewOp`. In any case, we can add the `name` parameter to the interface of `copy()`, and change the implementation later.

**Comment by rizar** [comment]
Sounds reasonable. Should I take any action like creating a Theano issue?

**Comment by lamblin** [comment]
Creating a Theano issue would be nice, thanks. I think we could tag it CCW and give it to a beginner this fall.

**Comment by rizar** [comment]
I created an issue. This indeed could be a CCW. It is not urgent, but it would be helpful for Blocks users, since we use `.copy` a lot.

**Comment by dwf** [comment]
Theano/Theano#3369 was just merged.
