### ISSUE TITLE
error when use plot

### ISSUE THREAD

**Issue by YangXS** [mila-udem/blocks#791]
When I run the examples in the live plotting documents,  the following errors appeared : 

ERROR:/usr/local/lib/python2.7/dist-packages/bokeh/validation/check.pyc:W-1001 (NO_GLYPH_RENDERERS): Plot has no glyph renderers: Figure, ViewModel:Plot, ref _id: 2f872f9d-fe0c-43b8-b814-18aace23b976
.
.
.
AttributeError: unexpected attribute 'y_axis_label' to Line

**Comment by rizar** [comment]
@janchorowski , I believe it is your change affecting people. Can you please check?

**Comment by leconteur** [comment]
I have this bug too.

**Comment by rizar** [comment]
Can you please try to install Bokeh version 0.9.0? It looks like you are now using 0.9.1 with which are currently unfortunately not compatible.

**Comment by janchorowski** [comment]
I can run the example, however both with my patch and without it I get an empty which seems similar to https://github.com/mila-udem/blocks-extras/issues/20

Which versions of bokeh are you using?

**Comment by YangXS** [comment]
@rizar 
I reinstalled the Bokeh version 0.9.0 and get the same problem as mila-udem/blocks-extras#20

**Comment by rizar** [comment]
It was reported that it goes away with a browser update. Can you check if there is one available for your browser? Or maybe try a different one?

**Comment by janchorowski** [comment]
Also try cleaning browser cache

**Comment by YangXS** [comment]
@rizar ， @janchorowski ，

Thanks for your help.

I finally have the live plotting on the browser by the following change:
(1) Add the argument open_browser = ture for the Plot function in line 236 of draw/train-draw.py
(2) Change show() to show(p) in line 110 of blocks-extras/blocks/extras/extensions/plot.py

**Comment by dwf** [comment]
This should really be on the blocks-extras repo and I think my pending pull request fixes this (by removing `open_browser` entirely), so closing.
