### ISSUE TITLE
can only have top level brick per class with same class name

### ISSUE THREAD

**Issue by dribnet** [mila-udem/blocks#793]
blocks seems to have a restriction that doesn't allow two top level bricks with the same class name. This came up for me when I tried to have a cost function that was the weighted sum of two BinaryCrossEntropy values and got the exception:

```python
ValueError: top bricks with the same name: binarycrossentropy
```

My workaround currently is to make a dummy subclass of `BinaryCrossEntropy` (though this has caused its own issues because then that class is not pickled correctly).

**Comment by dmitriy-serdyuk** [comment]
You can always specify the name of a brick: `BinaryCrossEntropy(name='my_binarycrossentropy')`.

**Comment by dribnet** [comment]
Aha - thanks!
