### ISSUE TITLE
error in the documents of the RNN 

### ISSUE THREAD

**Issue by YangXS** [mila-udem/blocks#802]
In the documents about the recurrent neural networks: http://blocks.readthedocs.org/en/latest/rnn.html, 
it seems that the connections from the bottom layer to the second layer are missing in the Figure of the Iterate (or not) section. According to the class definition of FeedbackRNN  below the Figure, the output of the first layer is inputted to the second layer in the apply function.

![image](https://cloud.githubusercontent.com/assets/4171290/9268406/39348b88-4291-11e5-8f78-6a832564ffca.png)

        ...
        @recurrent(sequences=['inputs'], contexts=[],
                   states=['first_states', 'second_states'],
                   outputs=['first_states', 'second_states'])
        def apply(self, inputs, first_states=None, second_states=None):
            first_h = self.first_recurrent_layer.apply(
                inputs=inputs, states=first_states + second_states, iterate=False)
            second_h = self.second_recurrent_layer.apply(
                inputs=first_h, states=second_states, iterate=False)
            return first_h, second_h
        ...

**Comment by rizar** [comment]
Agreed, the picture is wrong! A fix in the picture would be appreciated.

**Comment by pouyaAB** [comment]
I tried to fix the figure but I don't know if I write it correct or not since I couldn't see the preview!

**Comment by rizar** [comment]
You can build documentation locally using sphinx-build.

**Comment by pouyaAB** [comment]
Thank you...okay I fixed the figures I think and sent a pull request.

**Comment by vdumoulin** [comment]
Closed by #951.
