### ISSUE TITLE
Pass keyword arguments to 'theano.function' call in GradientDescent

### ISSUE THREAD

**Issue by dwf** [mila-udem/blocks#804]
`THEANO_FLAGS=mode=ProfileMode` is deprecated in favour of `profile=True` passed to `theano.function`.

**Comment by rizar** [comment]
I  think we should just let use pass some arguments to the `theano.function` call. What do you think?

**Comment by dwf** [comment]
That'd be fine, yeah.

**Comment by rizar** [comment]
Renamed the issue, added CCW label.

**Comment by dwf** [comment]
@rizar Where do you suppose those arguments should go? As `**kwargs` of `GradientDescent.initialize` maybe?

@orhanf How does this sound for a CCW ticket this week?

**Comment by orhanf** [comment]
so is it something like 63211cc07a595c3f2c83f0e60dd9394326e1b7e7 ? (without [this](https://github.com/mila-udem/blocks/blob/63211cc07a595c3f2c83f0e60dd9394326e1b7e7/blocks/algorithms/__init__.py#L240) line of course)

**Comment by dwf** [comment]
Hmm, I think what @rizar had in mind was a way to pass arbitrary kwargs along to theano.function.

**Comment by rizar** [comment]
Sure, I meant arbitrary kwargs.

**Comment by dwf** [comment]
Fixed by #823.
