### ISSUE TITLE
Decoder LSTM

### ISSUE THREAD

**Issue by escopeta** [mila-udem/blocks#806]
Hi,

Is there a way to create a decoder LSTM that doesn't observe anything from the input gate and only decodes from h_t outputted by an encoder LSTM?

Thanks.

**Comment by dmitriy-serdyuk** [comment]
This kind of questions is more suitable for [mailing list](https://groups.google.com/forum/#!forum/blocks-users). Can you move the topic there and elaborate a little, seems you are confusing encoder-decoder terminology and inner parts of LSTM.

**Comment by escopeta** [comment]
I am talking about encoding-decoding LSTM in the fashion described by this paper:
http://arxiv.org/pdf/1502.04681.pdf

Mainly the unconditioned version. I will go to the mailing list and post my question with the paper so it can be better illustrated.
