### ISSUE TITLE
drop_prob and rescaling should be set independently

### ISSUE THREAD

**Issue by JesseLivezey** [mila-udem/blocks#807]
Currently, ```apply_dropout``` rescales the replacement variables by ```(1-drop_prob)```, a more general case is to rescale by an arbitrary amount and use ```(1-drop_prob)``` as the default. I've found (in agreement with others' results) that setting them independently can lead to better results.

**Comment by dwf** [comment]
Agreed. The examples in pylearn2 were actually the result of a misunderstanding, but the seem to have uncovered something useful.
