### ISSUE TITLE
SQLiteLog relies on WITH clause syntax not available on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by mjwillson** [mila-udem/blocks#824]
According to http://www.sqlite.org/changes.html this was added in 3.8.3, Ubuntu 14.04 LTS only has 3.8.2 :-(
As a result I get `OperationalError: near "WITH": syntax error`. If the use of WITH could be avoided this would be a lot easier to use on Ubuntu.

**Comment by mjwillson** [comment]
Part of why this is a pain is the sqlite3 bindings appear to be part of the python stdlib itself, so hard to upgrade without rebuilding python (and installing it in a custom location, since ubuntu doesn't want its system python stomped on).

I was hoping I might be able to rephrase the WITH clause as subquery, but it's recursive too :(

**Comment by dwf** [comment]
Oy, who the hell adds brand new features to an established package in a
3rd-point release?

@bartvm wrote the SQLite stuff but it hasn't seen a ton of use yet, I don't
think. Bart, thoughts?

Personally I'd recommend using anaconda/miniconda, conda environments are
the only thing keeping me sane these days.

**Comment by mjwillson** [comment]
Yeah kinda funny versioning policy they have!

Personally I'm running into out-of-memory issues with the in-memory TrainingLog -- after running for a day or two (around 15million iterations) my machines run out of RAM and stop responding over ssh. I still need to confirm for sure (I'll report back) but TrainingLog seems the likely culprit.

For that reason something not entirely in-memory would be nice. It could be dead simple for all I care (e.g. a CSV file or a log with one JSON entry per line), just something I can recover the data from after the run.

**Comment by bartvm** [comment]
If someone can find an alternative SQL query I have no problem getting rid of the `WITH` clause, but it's a pretty nasty query to code without it I think (can't remember exactly how I got to the current query). You could do it in Python instead, but that could result in many database queries, which could slow things down (considering it's used in `__getitem__`, which could be called very often).

Writing a CSV or JSON database backend is very straightforward *if* we don't support multiple resumptions/branching, otherwise it's probably a whole lot more difficult (and not user-readable anymore).

**Comment by mjwillson** [comment]
Yeah I had a think about it, the recursive query is kinda tricky to rewrite. You'd probably have to resort to a loop with one query per iteration to fetch the ancestors, which might be rather slow.

I'm also not fully sure I understood the hierarchical data model for this stuff, I guess it's because multiple resumptions could branch off at any point? Perhaps in these cases you could just make a separate copy of the log you're branching off from, in order to keep the data model simpler?

**Comment by mjwillson** [comment]
I'm happy to have a go at implementing a simpler persistent TrainingLog that doesn't need to support multiple resumption branches -- I'd be a bit nervous to touch any branching related functionality though as I'm not using it myself and I'm not sure the tests cover the desired behaviour.

**Comment by mjwillson** [comment]
Can confirm that training log was the memory leak.
Seems it takes a minimum of 288 bytes per iteration, and as much as 680 bytes with an extension like timing turned on. At that rate it takes about 1.5m iterations to fill up a GB of RAM.

In [76]: print(asizeof.asized(main_loop.log[1], detail=1).format())
{'time_read_data_this_batch': 0.000144....d_data_total': 0.00014427900168811902} size=680 flat=288
    [K] time_read_data_this_batch size=80 flat=80
    [K] time_train_this_batch size=72 flat=72
    [K] time_train_total size=72 flat=72
    [K] time_read_data_total size=72 flat=72
    [V] time_read_data_this_batch: 0.00014427900168811902 size=24 flat=24
    [V] time_train_this_batch: 0.0037737679995188955 size=24 flat=24
    [V] time_train_total: 0.0037737679995188955 size=24 flat=24
    [V] time_read_data_total: 0.00014427900168811902 size=24 flat=24

(note the string keys are duplicated on every iteration)

**Comment by dwf** [comment]
So... what's the resolution of this?

**Comment by bartvm** [comment]
I wouldn't immediately know how to rewrite that SQL query, so I would go for `wontfix` and tell people to use Anaconda (if Ubuntu hasn't updated their Python distribution already)
