### ISSUE TITLE
Improve visibility of Blocks-examples and add comments

### ISSUE THREAD

**Issue by rizar** [mila-udem/blocks#830]
Currently Blocks README does not even mention Blocks-examples. The same goes for the documentation. Also, the examples should be more documented, because in fact they are a very (the most?) important part of all the help we provides for the users.

@fvisin , did I understand you right that you would be eager to take care of it?

**Comment by fvisin** [comment]
I went through part of the documentation of Blocks and I took notes on what I would modify or improve. I volunteer to go through the rest of the documentation on www.blocks.readthedocs.org and improve it. I can also skim through the examples in Blocks-examples and add some comments, but it was not my main goal right now.

**Comment by dwf** [comment]
I think there's already an open issue on blocks-examples to document them
better.

I think the first thing to do is to document your problems with the
documentation in the form of issues. It's fine if you don't do it all
yourself, in fact these make good beginner CCW tickets (for people with a
good command of English, anyway).

**Comment by fvisin** [comment]
I created https://github.com/mila-udem/blocks/issues/831

@dwf I would also like to propose the rewording of a couple of sentences that I find ambiguous or not informative enough, but for that if you agree I would directly work on a PR (as soon as I have time), as it will take the same time to write what I would change and actually change it. Also, I think it will be easier to discuss my proposal in the PR in that case, as the modification will be sparse and local.

**Comment by dmitriy-serdyuk** [comment]
Is it fixed?

**Comment by rizar** [comment]
This can be closed, because no we have links to Blocks-examples from Blocks.
