### ISSUE TITLE
validation set

### ISSUE THREAD

**Issue by moore269** [mila-udem/blocks#837]
Is there any way to use a validation set to select the best model while training? So far, it doesn't look like this is implemented. Thanks.

**Comment by dwf** [comment]
Have a look at the examples. You can use the `FinishIfNoImprovementAfter` extension to inspect the log, in concert with the `DataStreamMonitoring` extension to write to the log.

**Comment by dwf** [comment]
P.S. The blocks-users mailing list is a better front line support venue for this sort of question than the issue tracker, which is meant for known missing features and bugs.
