### ISSUE TITLE
"It is entirely transparent for the main loop"

### ISSUE THREAD

**Issue by dwf** [mila-udem/blocks#845]
https://github.com/mila-udem/blocks/blob/master/blocks/main_loop.py#L77-L78

Not sure what this means. Clarify.

**Comment by dwf** [comment]
If the claim is that MainLoop doesn't actually touch this, then the claim is wrong: https://github.com/mila-udem/blocks/blob/master/blocks/main_loop.py#L153

**Comment by rizar** [comment]
Point taken. This is now CCW though, this is `Model` refactoring which I am going to do... today!

**Comment by dwf** [comment]
Apparently been fixed for a while.

**Comment by dwf** [comment]
Seems like this has been solved a long time ago.
