### ISSUE TITLE
ConvolutionalActivation, ConvolutionalSequence do not honor use_bias=False

### ISSUE THREAD

**Issue by cooijmanstim** [mila-udem/blocks#847]
ConvolutionalActivation does not push use_bias to its Convolutional child, nor does ConvolutionalSequence:

    import theano.tensor as T

    from blocks.bricks import conv, Rectifier
    from blocks import initialization, graph

    cnn = conv.ConvolutionalSequence([
        conv.ConvolutionalActivation(
            activation=Rectifier().apply,
            filter_size=(1, 1),
            num_filters=1,
            use_bias=False)
        for _ in xrange(3)],
        num_channels=1, image_size=(1, 1),
        use_bias=False,
        weights_init=initialization.IsotropicGaussian(1e-3),
        biases_init=initialization.Constant(0))
    cnn.initialize()

    x = T.tensor4()
    y = cnn.apply(x)

    print graph.ComputationGraph(y).parameters

Removing biases (e.g. for batch normalization) requires reaching into internals.

**Comment by dwf** [comment]
They don't honour a lot of things, actually, including the `border_mode`.

**Comment by dwf** [comment]
My bad, actually: my comment was #681 at work.

**Comment by cooijmanstim** [comment]
In `test_convolutional_sequence_use_bias`, could you remove `use_bias=False` from the `ConvolutionalActivation` kwargs? I think that's what you intended to test there.

**Comment by dwf** [comment]
Ah, I had copied and pasted your code in that case, yes that would be a
better test.

**Comment by dwf** [comment]
@cooijmanstim corrected in 0e7c824
