### ISSUE TITLE
apply_dropout should default to 0.5 drop_prob

### ISSUE THREAD

**Issue by dwf** [mila-udem/blocks#854]
This is by far the most common case, so I think it's reasonable to have a default value.

Related to #848.

**Comment by dmitriy-serdyuk** [comment]
We discussed it: https://github.com/mila-udem/blocks/pull/407#discussion_r26138708 and I thought it's better not to give any default so the user code is more readable. It seemed to me that `0.5` in `apply_dropout(cg, vars, 0.5)` is not a big deal.

**Comment by dwf** [comment]
Alright, fair enough.
