### ISSUE TITLE
Use blaze and dask for streaming+out of core data?

### ISSUE THREAD

**Issue by datnamer** [mila-udem/blocks#869]
These are out of core array and table abstractions for a variety of backends (including numpy). Also have chunking and streaming capability.

See some of these : 
https://github.com/blaze/dask/pull/138

http://blaze.pydata.org/ 

Just an idea. Would be powerful to get projects cooperating on these common abstractions. Synergy+reduce maintenance cost.

**Comment by dwf** [comment]
The place to do that would probably be Theano and/or Fuel.

**Comment by datnamer** [comment]
Yes i meant to post this in fuel, sorry.
