### ISSUE TITLE
Crash when manually initializing GradientDescent

### ISSUE THREAD

**Issue by cooijmanstim** [mila-udem/blocks#870]
MainLoop initializes the algorithm regardless of whether it has already been initialized, and GradientDescent.initialize() adds the updates to self.updates, resulting in duplicate updates:

    ValueError: ('this shared variable already has an update
    expression, (<TensorType(float64, scalar)>,
    Elemwise{sub,no_inplace}.0)\n\nOriginal exception:\n\tValueError:
    this shared variable already has an update expression,
    (<TensorType(float64, scalar)>, Elemwise{sub,no_inplace}.0)',
    (<TensorType(float64, scalar)>, Elemwise{sub,no_inplace}.0))

To reproduce:

    import theano
    from theano import tensor
    from blocks.algorithms import GradientDescent, Scale
    from blocks.main_loop import MainLoop
    from fuel.datasets import MNIST
    from fuel.streams import DataStream
    from fuel.schemes import SequentialScheme

    a = theano.shared(1.)
    x = tensor.scalar()
    y = x + a

    mnist_train = MNIST(['train'])

    algorithm = GradientDescent(cost=y, parameters=[a])
    algorithm.initialize()

    main_loop = MainLoop(
        algorithm,
        DataStream(
            mnist_train,
            iteration_scheme=SequentialScheme(mnist_train.num_examples, 100)))
    main_loop.run()

**Comment by dwf** [comment]
It sounds like the problem is (possibly) twofold: the algorithm's initialize method doesn't do anything sensible when called a second time, and MainLoop is trying to initialize things it arguably shouldn't.

**Comment by rizar** [comment]
Oh, we really should just ignore second and subsequent calls to  algorithm!
That would make certain things simpler, e.g. we would not have to have a
weird record `training_started` in the log.
