### ISSUE TITLE
Bug in SequnceGenerator image in documentation

### ISSUE THREAD

**Issue by akhti** [mila-udem/blocks#895]
In this image (docs/_static/sequence_generator_scheme.png):
![](http://blocks.readthedocs.org/en/latest/_images/sequence_generator_scheme.png)
```take_look``` must be replaced with ```take_glimpses```
Could be fixed easily, by the source of the image is needed.

**Comment by rizar** [comment]
True! Thanks for pointing it out.

It was really hard to find the SVG file, but fortunately I found it. Please
see the latest PR.

**Comment by akhti** [comment]
OK, I'll fix the label as soon as the image reaches the repo. Do you by any change have the source image for #802 ?

**Comment by rizar** [comment]
@akhti , I merged svg file.

@vdumoulin , do you still have the .svg file for the recurrent bricks documentation that you wrote back in Spring?
