### ISSUE TITLE
PersistentCudaNdarrayID and PersistentSharedVariableID doesn't exsit in theano.misc.pkl_utils

### ISSUE THREAD

**Issue by JianboTang** [mila-udem/blocks#901]
line 20 : from theano.misc.pkl_utils import (PersistentCudaNdarrayID ,PersistentSharedVariableID)
in blocks/serialization.py
however, PersistentCudaNdarrayID and PersistentSharedVariableID aren't found in neither the 0.6 version of theano nor the 0.7 one
is there something wrong?
Thx

**Comment by sjtufs** [comment]
Maybe you should check again?
https://github.com/Theano/Theano/blob/master/theano/misc/pkl_utils.py#L155
