### ISSUE TITLE
ImportError: cannot import name PersistentCudaNdarrayID

### ISSUE THREAD

**Issue by astrung** [mila-udem/blocks#904]
I use block version 0.1.1 and theano version 0.7.0
And when i try to run examples from blocks-examples i get this error:ImportError: cannot import name PersistentCudaNdarrayID.(https://github.com/mila-udem/blocks-examples :  command : "python -m sqrt --num-batches 1000 sqrt/saved_state").How can i fix error?

**Comment by dwf** [comment]
As explained in the blocks docs, you'll need Theano from master on GitHub,
as there hasn't been a stable release of theano in a while.

**Comment by astrung** [comment]
I think theano version 0.7.0 is the latest stable version now???Or not??

**Comment by dwf** [comment]
Yes. Read my reply again. You will need an even more recent version of
Theano.

**Comment by astrung** [comment]
I have installed with this command:pip install theano??and it is latest stable version.So i need clone github:Theano or some other ways to do it??

**Comment by dwf** [comment]
http://blocks.readthedocs.org/en/latest/setup.html

**Comment by astrung** [comment]
But when i install from command in installation,i see that theano version still 0.7.0>>No new version even with github???

**Comment by rizar** [comment]
The cutting edge version on Github most likely has the same version number,
but nevertheless it has a lot of changes. You should see the installation
log and make sure that the code is fetched from GitHub.
