### ISSUE TITLE
Initialization for complicated bricks like LSTMs

### ISSUE THREAD

**Issue by dwf** [mila-udem/blocks#932]
It seems kind of crazy that you are limited to one weights_init and one biases_init in LSTMs, when you have so much going on inside an LSTM cell.

Compare with the configurability of the LSTM in Lasagne: https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/recurrent.py#L681-L692

@memimo

**Comment by rizar** [comment]
See #740, i tried to outline there a better way of initialization propagation.

**Comment by dwf** [comment]
Closed as duplicate of #740.
