### ISSUE TITLE
__call__ function in Application class?

### ISSUE THREAD

**Issue by Beronx86** [mila-udem/blocks#937]
Hi,
I read some code of the block library.
I am confused with the `__call__` function in the Application class in the file blocks/bricks/base.py
`Application` class implemented `__get__` function, so it is a descriptor. 
<pre><code>
class use_wrapper(object):
    @application
    def apply(self, \*args, \*\*kwargs):
        pass
uw= use_wrapper()
uw.apply
</pre></code>
When `uw.apply` is visited, the `__get__` method in Application class is called. And the `__call__` method of the Application class is never called. `uw.apply()` would call the `__call__` method in `BoundApplication` class. Is that right?
Is the `Application.__call__` method is used in the project?

I am also confused with how the arguments are passed in `application` function in blocks/bricks/base.py.
<pre><code>
class class_wrapper(object):
    ...

def wrapper(\*args, \*\*kwargs):
    if args:
        func, = args
        return class_wrapper(func)
    else:
        def _wrap(func):
            return class_wrapper(func)
        return _wrap

@wrapper(inputs='', output='')
def func():
     print "func called"

@wrapper
def func():
     print "func called"
</pre></code>
If I provide some keyword arguments when calling `wrapper` as a decrator, `args` would not receive `func` as an argument. If I call the wrapper directly, `args` would receive `func`. 
It is tricky. Could you provide some reference on this?

**Comment by Beronx86** [comment]
Besides would `__getattr__`, `__setattr__` function in Application class be called?
<pre><code>
    def \_\_getattr\_\_(self, name):
        # Mimic behavior of properties
        if 'properties' in self.__dict__ and name in self.properties:
            return property(create_unbound_method(
                getattr(self, self.properties[name]), self.brick))
        raise AttributeError

    def __setattr__(self, name, value):
        # Mimic behavior of read-only properties
        if 'properties' in self.__dict__ and name in self.properties:
            raise AttributeError("can't set attribute")
        super(Application, self).__setattr__(name, value)
<\pre><\code>
The implementation of `__getattr__` seems wrong.  The second argument of `getattr` is callable in the code, but should it be a string?

**Comment by wenhuchen** [comment]
Decorator has different behaviors when called with and without argument. When called without argument, the outermost layer will receive the function as an argument, while called with argument like @application(input=...,output=....), then the outermost layer will receive keyword arguments (input=...,output=...) as argument, the actual function will be passed into the inner layer as an argument.

**Comment by rizar** [comment]
That's a great answer, and it seems like the discussion has moved to a more recent ticket #939.
