### ISSUE TITLE
TrainingDataMonitoring cause algorithm hang at initialization

### ISSUE THREAD

**Issue by zxvix** [mila-udem/blocks#938]
I recently found that when monitoring an output using TrainingDataMonitoring, but the output requires an input that is not in the computation graph of the cost, main loop will hang at "Initializing the training algorithm". My current solution is to modify _cost_computation_graph in DifferentiableCostMinimizer to be the computation graph of all the outputs.  Is this a problem of the algorithm or of my particular setting?

**Comment by dwf** [comment]
Can you give us a minimal example that reproduces the problem?

**Comment by zxvix** [comment]
When I try to reproduce it in a minimal script ('output_1' has 'input_3' which is not an input of 'cost'):

    from fuel.datasets.toy import Spiral
    from theano import tensor
    from blocks.bricks import Linear
    from blocks.main_loop import MainLoop
    from blocks.graph import ComputationGraph
    from blocks.algorithms import GradientDescent, AdaGrad
    from blocks.model import Model
    from blocks.extensions.monitoring import TrainingDataMonitoring
    
    input_1 = tensor.matrix('features')
    input_2 = tensor.vector('position')
    input_3 = tensor.vector('label')
    
    layer = Linear(input_dim=2, output_dim=1)
    
    cost = tensor.sum(layer.apply(input_1) + input_2)
    cost.name = 'cost'
    output_1 = tensor.sum(layer.apply(input_1) + input_3)
    output_1.name = 'output_1'
    
    dataset = Spiral()
    
    main_loop = MainLoop(model=Model(cost),
                         algorithm=GradientDescent(
                                 cost=cost, parameters=ComputationGraph(cost).parameters,
                                 step_rule=AdaGrad()),
                         data_stream=dataset.get_example_stream(),
                         extensions=[
                             TrainingDataMonitoring([cost, output_1],  after_epoch=True)])
    main_loop.run()
I instead get an exception:

    theano.gof.fg.MissingInputError: A variable that is an input to the graph was neither provided as an input to the function nor given a value. A chain of variables leading from this input to an output is [label, DimShuffle{x,0}.0, Elemwise{add,no_inplace}.0, output_1, Elemwise{add,no_inplace}.0, GpuFromHost.0]. This chain may not be unique

If I want to make this example work, what should be done?

**Comment by rizar** [comment]
It says that you do no provide 'label' to a Theano function. A stack trace would be helpful.

**Comment by zxvix** [comment]
I assume that GradientDescent found the correct set of inputs when building the Theano function. The problem here is TrainingDataMonitoring introduced a new input (the 'label'), which probably should be added to self.inputs of GradientDescent?

**Comment by rizar** [comment]
That sounds reasonable, but a stack trace is still highly desirable

**Comment by dwf** [comment]
@rizar "label" is a source provided by `Spiral` so it should get filled in as the value for `input_3`. I don't know why it doesn't.

Just to confirm, does this run without the `TrainingDataMonitoring` exception?

**Comment by zxvix** [comment]
Using theano flags `optimizer=None` and `exception_verbosity=high` doesn't give me more output.

@dwf I tried to understand the problem, and found that when the theano function is built [here](https://github.com/mila-udem/blocks/blob/25c514157eb95bb670c4eac0740f2e3b6962e740/blocks/algorithms/__init__.py#L252), it's using `self.input` as the input of the theano function, which is from [here](https://github.com/mila-udem/blocks/blob/25c514157eb95bb670c4eac0740f2e3b6962e740/blocks/algorithms/__init__.py#L110). These are the inputs of `cost` only, which does not include "label" in this case.

without `TrainingDataMonitoring` "label" will become an unused source.

**Comment by rizar** [comment]
Yes, indeed, we have here a situation when `TrainingDataMonitoring` adds an input which the cost graph does not have, and it effectively breaks `GradientDescent`. A quick fix would be to ensure that there is a dependency of cost on 'label', let it be a degenerate one, like `cost = cost + 0 * label`. A proper fix would determine the inputs of `GradientDescent` using `self.updates`.
