### ISSUE TITLE
ProgressBar extension not working with Fuel transformers?

### ISSUE THREAD

**Issue by hsintone** [mila-udem/blocks#948]
I'm trying to use the ProgressBar extension, but it doesn't seem to be able to get the iteration scheme of my datastream, so I only get the BouncingBar. I believe line 455 of the `__init__.py` file of the extensions is the cause of the problem:
```Python
    iter_scheme = self.main_loop.data_stream.iteration_scheme
```
I made a simple datastream with a transformer:
```Python
    ds = ForceFloatX(DataStream.default_stream(dataset, iteration_scheme=SequentialScheme(num_total, batch_size=batch_size)))
```
And made the same tiny main loop as in the tests for ProgressBar. Now printing the iteration scheme the way the extension tries to find it results in `None`:
```Python
    In [74]: print main_loop.data_stream.iteration_scheme
    None
```
If I remove the ForceFloatX transformer it works fine. This works with the transformer but not without it:
```Python
In [75]: print main_loop.data_stream.data_stream.iteration_scheme
<fuel.schemes.SequentialScheme object at 0x7fead0f2fb10>
```

Am I doing something wrong or is there a bug? If it's a bug, would simply adding an if-statement to check which one is not `None` be enough to fix it or would it break something else? Or would the references to the data_streams grow with the number of transformers used?

**Comment by bartvm** [comment]
This is expected behaviour. The problem is that transformers could conceivably change the iteration scheme (e.g. by discarding examples or adding new ones). There should be a way for transformers to announce what their iteration scheme (or just `num_batches`/`num_examples`) are, but that currently isn't implemented.

Also see the discussion at https://github.com/mila-udem/blocks/pull/549

**Comment by hsintone** [comment]
Ah, I see. Thank you for letting me know. 

Would there be any differences in implications or code complexity whether the transformers would default to `None` or to the `num_examples` / `num_batches` / iteration scheme of the previous link in the chain? (In both cases they could change what they report onwards if they messed with the scheme.)

**Comment by dwf** [comment]
Defaulting to the `num_examples` / `num_batches` / etc. from the previous link in the chain would be quite dangerous. `None`, I'm not sure.

**Comment by rizar** [comment]
This seems to a be a fundamental issue.
