### ISSUE TITLE
When to use @application without argument

### ISSUE THREAD

**Issue by wenhuchen** [mila-udem/blocks#949]
Hello,

I'm quite confused at the moment about the application decorator. I read the machine_translation example, I understand that the functions with @application(arguments) decorator is used to build computational graph with annotated variable names. 
But what's the purpose of having @application without any argument, then it can't build any part of the computational graph. Like the sequence generator is with all the decorator without arguments, which confuses me a lot, how can it finds the "sequence,context,inputs" variable?
Can you help me with it?

**Comment by rizar** [comment]
Decorating with @application without arguments can still be very helpful.
This way the variables in the computation graph are annotated with pointers
to the brick and to the application methods that created them. Also, if a
method of a brick calls an application method  of another brick, it must be
decorated.

**Comment by dwf** [comment]
@wenhuchen Closing this as it seems your question was answered, feel free to reopen if not.
