### ISSUE TITLE
Subtle issue with Application serialization

### ISSUE THREAD

**Issue by dwf** [mila-udem/blocks#958]
This test currently fails with an assertion error in the implementation failing.

```python
from theano import tensor
from blocks.bricks import BatchNormalization
from blocks.graph import ComputationGraph, apply_batch_normalization


def test_batch_normalization_deserialized():
    y = BatchNormalization(input_dim=5).apply(tensor.matrix())
    yprime = cPickle.loads(cPickle.dumps(y))
    from blocks.graph import ComputationGraph
    apply_batch_normalization(ComputationGraph([yprime]))
```

The issue seems to be that the `Application` wrapper object gets deserialized along with the graph, and the one currently attached to the `BatchNormalization` class does not compare equal to the deserialized one.

I can think of a few ways to solve this:

* The most obvious is to change the assertion to look at `application.name` and 
* Add some `__setstate__` and `__getstate__` or maybe `__new__` magic to make sure that these objects are replaced by their equivalents that are instantiated when the interpreter evaluates the class (this is aesthetically the nicest, since it futureproofs against changes to `Application` and also prevents there being two objects in memory that represent `Foo.apply`).
* Implement `__eq__` on `Application` so that non-identical objects at least compare equal if they *represent* the same application.

**Comment by dwf** [comment]
(@vdumoulin found this, I just created the test case)

**Comment by bartvm** [comment]
`q` = `yprime` I guess?

**Comment by vdumoulin** [comment]
Yes. Here's a working version of the code reproducing the issue:

``` python
from six.moves import cPickle
from theano import tensor
from blocks.bricks import BatchNormalization
from blocks.graph import ComputationGraph, apply_batch_normalization


def test_batch_normalization_deserialized():
    y = BatchNormalization(input_dim=5).apply(tensor.matrix())
    yprime = cPickle.loads(cPickle.dumps(y))
    from blocks.graph import ComputationGraph
    apply_batch_normalization(ComputationGraph([yprime]))
```

I confirm that it's also failing on my end.

**Comment by dwf** [comment]
Yeah, updated my version. Changed variable name just before paste.

**Comment by rizar** [comment]
```
Implement __eq__ on Application so that non-identical objects at least
compare equal if they *represent* the same application.
```

This sounds practical, though still having two objects in memory instead of
one is a potential trap.

```
Add some __setstate__ and __getstate__ or maybe __new__ magic to make sure
that these objects are replaced by their equivalents that are instantiated
when the interpreter evaluates the class (this is aesthetically the nicest,
since it futureproofs against changes to Application and also prevents
there being two objects in memory that represent Foo.apply).
```

That would be cool, but I am not sure if it is possible.

**Comment by rizar** [comment]
A flashback occurred to me, and I remember that [copy_reg] should be the solution. As far I understand with this module we can hack pickling machinery to save a string instead of an `Application` instance, and upon unpickling replace this string with the existing `Application` object.
