### ISSUE TITLE
ImportError: cannot import name bn

### ISSUE THREAD

**Issue by DanlanChen** [mila-udem/blocks#978]
Does somebody knows why I have this error?
>> import blocks
>>> from blocks.bricks import bn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/blocks/bricks/__init__.py", line 3, in <module>
    from .bn import (BatchNormalization, SpatialBatchNormalization,
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/blocks/bricks/bn.py", line 7, in <module>
    from theano.tensor.nnet import bn
ImportError: cannot import name bn

**Comment by rizar** [comment]
Can you try to update your Theano to the cutting edge version?

**Comment by dwf** [comment]
Blocks requires bleeding edge Theano from the master branch. This was added to Theano in September,  where the last stable Theano was last March.

**Comment by DanlanChen** [comment]
Thanks , it fixed my problem

**Comment by elishaROBINSON** [comment]
downloaded and installed the latest master does bn only appear on a specific version of theano

**Comment by rizar** [comment]
No, it is in the master branch.

**Comment by elishaROBINSON** [comment]
Okay I went to theano git cloned it used setup.py install . the theano.version gives me this < module 'theano.version' from '~/py2.7/site packages/Theano-0.9.0.dev0-py2.7.egg/ theano/version.pyc,> .thanks in afvanc

**Comment by KangolHsu** [comment]
sudo apt-get install python-dev python-pip python-nose g++ git gfortran liblapack-dev libatlas-base-dev libopenblas-dev Cython
# the cutting-edge development version.(requirements.txt show what has been installed)
sudo pip install git+git://github.com/mila-udem/blocks.git \
  -r https://raw.githubusercontent.com/mila-udem/blocks/master/requirements.txt

git clone https://github.com/IshmaelBelghazi/ALI.git
sudo pip install -e ALI

cd ALI
mkdir DATA
fuel-download cifar10
fuel-convert cifar10

THEANORC=theanorc python experiments/ali_cifar10.py
