### ISSUE TITLE
Identity name clash for Identity(Activation) and Identity(NdarrayInitialization)

### ISSUE THREAD

**Issue by arvieFrydenlund** [mila-udem/blocks#999]
Basically you have two Identity classes, one the activation and one the initialization and this leads to an easy mistake.  Obviously there are (multiple) simple ways of getting around this, and I am mostly writing this ticket just so the issue is online for other people in case they hit the same issue.   It comes up with the basic example of an RNN having both identity activation and initialization.  

This comes up in this example:
```
#note I missed the import from blocks.intialization and no issue arose because the name was imported elsewhere
from blocks.initialization import Constant, Uniform, IsotropicGaussian
from blocks.bricks import Identity, Initializable, Linear

self.rnn = SimpleRecurrent(
            dim=self.input_dim3, activation=Identity(), name='rnn',
            weights_init=Identity())
```

Which results in this error

> Traceback (most recent call last):
  File "/u/arvie/PHD/Neural_Language_Models/Shared_Model_layers/Compositional_Layer.py", line 552, in <module>
    language_model_toy.initialize()
  File "/u/arvie/.local/lib/python2.7/site-packages/blocks/bricks/base.py", line 649, in initialize
    child.initialize()
  File "/u/arvie/.local/lib/python2.7/site-packages/blocks/bricks/base.py", line 650, in initialize
    self._initialize()
  File "/u/arvie/.local/lib/python2.7/site-packages/blocks/bricks/recurrent.py", line 303, in _initialize
    self.weights_init.initialize(self.W, self.rng)
TypeError: initialize() takes exactly 1 argument (3 given)

It is easy to change this to work by either doing

`from blocks.initialization import Identity as Identity_init`

or 

```
from blocks import initialization
self.rnn = SimpleRecurrent(
            dim=self.input_dim3, activation=Identity(), name='rnn',
            weights_init=initialization.Identity())
```

which is what was done in the tutorials.

**Comment by dwf** [comment]
Right, realistically I don't think this is something we will change, as this is exactly what namespaces and import renames are for.
